### ISSUE TITLE
FR: generate html file from emmet on command line

### ISSUE THREAD

**Issue by dizzib** [emmetio/emmet#112]
I'd like to be able to take an emmet file, say foo.emmet, and generate foo.html:

```
emmet [ options... ] [ filename ]
```

For example, the following would generate ~/out/foo.html from ~/in/foo.emmet

```
emmet -o ~/out ~/in/foo.emmet
```

It might make sense to use Nodejs for this. Cheers!
##

**Comment by sergeche** [comment]
You can wrap current repo into CLI tool, it’s just abbreviation expander now
