### ISSUE TITLE
Formatting CSS properties in a single line (compact format)

### ISSUE THREAD

**Issue by ricardozea** [emmetio/emmet#114]
Although not an issue per se, I wasn't able to see where I could modify Emmet's default CSS formatting from "expanded" (properties+values each in a single line) to compact (all properties+values in a single line).

For example, Emmet's current CSS default formatting (expanded):

```
header {
       width:960px;
       height:120px;
}
```

To this style (compact):
   `header { width:960px; height:120px; }`

Any idea how to accomplish this?

Thanks.

**Comment by theZimmee** [comment]
When I have single line formatting for CSS enabled, it strips `\n` new lines from my snippets. Is there a way around this?
