### ISSUE TITLE
Vim plugin

### ISSUE THREAD

**Issue by iurevych** [emmetio/emmet#124]
Do you have plans to support Vim editor?
##

**Comment by uuhan** [comment]
div>ul>li <C-y>, becomes
1<div>
2      <ul>
3         <li> </li>
4      </ul>
5</div>
there is an additional space between <li> and </li> in line no. 3
Why? Is it a feature or just because I made some thing wrong?
Thx
~

**Comment by uuhan** [comment]
div>ul>li <C-y>,
In the line No. 3, there is an additional space comes out between <li>and</li>
Why? Is it a feature or just because of something wrong I made?
Thx

**Comment by uuhan** [comment]
div>ul>li \<C-y>,
In the line No. 3, there is a space comes out between \<li> and \</li>
Why? Is it a feature or just because of something wrong I made?
Thx

**Comment by wsdjeg** [comment]
```vim
NeoBundle 'mattn/emmet-vim'
let g:user_emmet_install_global = 0 
let g:user_emmet_leader_key='<C-e>'
let g:user_emmet_mode='a'
autocmd FileType html,css,jsp EmmetInstall
```
it works fine for me in jsp html css
