### ISSUE TITLE
Allowing boolean attributes

### ISSUE THREAD

**Issue by planetoftheweb** [emmetio/emmet#160]
When I type the following text into an editor that understands emmet:

div.fragment>pre>code.javascript[contenteditable]
it expands to:

```
<div class="fragment">
    <pre><code class="javascript" contenteditable=""></code></pre>
</div>
```

Which is almost perfect, except that the boolean attribute shouldn't have the quotes. Would it be possible modify the statement above so that it creates nodes with boolean attributes with no values. Right now, I have to manually delete the ="" sign. Thanks

```
<div class="fragment">
    <pre><code class="javascript" contenteditable></code></pre>
</div>
```

**Comment by tucq88** [comment]
Awesome. This should be include in [cheatsheet](http://docs.emmet.io/cheat-sheet/) or official guide. It's very helpful in the world of AngularJS/ReactJS now
