### ISSUE TITLE
Is Emmet working with Notepad++ 6.3 ?

### ISSUE THREAD

**Issue by Interned** [emmetio/emmet#166]
I've got Notepad++ 6.3 ands Windows 7.
Emmet has been installed because there's "Emmet" menu item in top menu and shortcuts have been edited.
But it seems to be not working cause it's inactive. What have I made wrong ?

N.B. : The link you provided if we don't see Emmet in Notepad++ isn't dealing with Win7, see below :
_Supported operating systems: Windows 2000, Windows 98 Second Edition, Windows ME, Windows NT, Windows Server 2003, Windows XP_

Kind regards,

T.

**Comment by englishextra** [comment]
Rebind 2 shortcuts ```insert blank line above / below``` to ctrl+alt+up/down
Then you're gonna have no conflcts

**Comment by khandakershahi** [comment]
while in css file, I write color than press tab and it change to 

> column-rule: ;

and also with margin

> max-resolution: res;

.
why is that. 
win7 64, notepad++ v7.5.4 32bit.
