### ISSUE TITLE
Нечитабельный текст docs.emmet.io

### ISSUE THREAD

**Issue by ghost** [emmetio/emmet#172]
Убрал с `body`

``` css
color: #777;
font-weight: 300;
```

До (сплошные Вырвиглаз)
![ 2013-02-25 00 47 46](https://f.cloud.github.com/assets/1616261/190187/3c9b1568-7ed4-11e2-9191-58053d7b01fd.png)

После
![ 2013-02-25 00 47 38](https://f.cloud.github.com/assets/1616261/190188/41429262-7ed4-11e2-83f3-1c1e7ab84721.png)
##

**Comment by sergeche** [comment]
Скоро полностью переделаю все сайты
