### ISSUE TITLE
notepad++ 6.3 python

### ISSUE THREAD

**Issue by Merg1255** [emmetio/emmet#185]
I've installed Emmet on a fresh notepad++ installation, turn on the python script console, and here's what the console says when trying to expand an abbreviation:

Traceback (most recent call last):
  File "<string>", line 2, in <module>
ImportError: No module named npp_emmet
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'npp_emmet' is not defined
##

**Comment by lwd1900** [comment]
hi
i have notepad++ version 6.8.2

Emmet plugin 1.0.0 

python script 1.0.6.0

Emmet is  no  work..........

What can I do? Thanks in advance.

**Comment by bruderstein** [comment]
@lwd1900 try installling python script from the MSI (sorry still sourceforge- http://sourceforge.net/projects/npppythonscript/) or look at the console to see if there are any errors (plugins -> python script -> show console). If you don't see anything in the console, it's possible you're missing a startup.py.  The MSI will fix this.
