### ISSUE TITLE
BUG: Image data URI encode glitch

### ISSUE THREAD

**Issue by byzod** [emmetio/emmet#238]
**Emmet version**: notepad++ plugin 1.0.0
**Platform**: Windows 7 x64, notepad++ 6.3.3

**Problem**: The "Encode/decode image to data:URL" function partially broken

**Reproduce steps**:(please download the attachment)
A: Decode fail
- Open `test.html` with notepad++ (with Emmet installed of course)
- Click on the base64 chunk of `src` section, select `Encode/decode...to data: URL` menu item
- A prompt appear, enter `b.png` then enter, a new b.png appear, but it's broken which contains strange binary bytes

B​:​​ Encode image within folder contains characters sometimes fail​
- Change the `src​` ​of `<img>` tag to `a.png`, encode, success
- Change the src to `test/a.png`, encode, success
- `test test/a.png` or `test%20test/a.png`, **failed**
- `test;test/a.png` ​or `test%3Btest/a.png`, **failed**
- `test-test/a.png`, success​

Test case: http://www.mediafire.com/download/321cjq4lg19x2ae/Emmet_test.7z
##

**Comment by sergeche** [comment]
Please reopen if it’s still relevant
