### ISSUE TITLE
Issues installing Emmet plugin in Notepad++

### ISSUE THREAD

**Issue by IzzoMcphibbit** [emmetio/emmet#241]
Can anyone help me? I'm trying to install the Emmet plugin in Notepad++, but am getting the following error message:

"It has not been possible to validate the integrity of 'EmmetNPP 'needed to install or update a plugin.Do you want to copy this file anyway (not recommended)?"

Help!

**Comment by mohit4312** [comment]
both emmet and python plugin are not available in plugin manager.
please tell me what to do know?
