### ISSUE TITLE
Plugin sometimes working slow in Dreamweaver

### ISSUE THREAD

**Issue by yxchai** [emmetio/emmet#256]
Hi Sergey,

I've been using Emmet in sublime and Dreamweaver. I'm an Email Developer. So most of the time I'm working in Dreamweaver. But it seems like under some unknown situation, the plugin is slowing Dreamweaver. And I got this alert occasionally. Check below.

![image](https://f.cloud.github.com/assets/622364/1155555/f5ca683e-1f71-11e3-8ee3-df0fb6e74e9e.png)

Also I have further info if you needed. Like what kind of HTML and which line will cause this kind of issue. 

If you need more info, I can provide to you. 

Thank you for your every effort put in Emmet!
Fantastic.

Woody
##

**Comment by sergeche** [comment]
DW plugin is not supported anymore, closing
