### ISSUE TITLE
Put line breaks in text

### ISSUE THREAD

**Issue by fversepuy** [emmetio/emmet#285]
Hi,

I like to use Emmet multiplication operator combined with curly braces (for text), instead of making a multiple copy past. For example, let's say i have this line : 
"This is a text <?php //even with php tags, or html tags, why not ?> I mean something I don't want or I can't write using Emmet syntax..."

What I do is just putting curly braces and a multiplier, like this, and expand : 
{This is a text <?php //even with php tags, or html tags, why not ?> I mean something I don't want or I can't write using Emmet syntax...}*20
In most cases this is faster than copy-pasting 20 times or so...

Problem is that Emmet expand it on a single line, and I'd like to have it with line breaks. I tried putting "\n", "\t", "\n\t" and so on, at the end of the text, before the closing curly brace, but didn't work. Any idea? Is it possible?
ps : I'm using Emmet with Dreamweaver, but i think this issue is independent of the text editor. 

Thanks!

**Comment by xpectmore** [comment]
not sure if will work on your editors but here in Editplus (editplus.com)  the best editor since '98  ,
i edit snippets.json and i insert inside ..
```
"cc:noie": "<!--[if !IE]><!-->\n\t${child}|\n<!--<![endif]-->", <-----this comma
			"php": "<?php\r\n\r\n?>"   <-------------------------that code
		},
		
		"abbreviations": {
```


so 
,
"php": "<?php\r\n\r\n?>"

ans seems that **php** will transform in
<?php

?>

I REPEAT **here in editplus**  now i should figure out how to move the cursor inside..

**Comment by 9p6** [comment]
> `{some text${newline}}*20

Exactly what I needed but I wish it was a little bit less verbose
