### ISSUE TITLE
Allow multiple items output positions in "Wrap with Abbreviation"

### ISSUE THREAD

**Issue by riddlew** [emmetio/emmet#303]
From what I have seen there is not a feature added like this yet. I would like to request that the feature be added so that multiple arguments can be used with Wrap with Abbreviation. For example, using the following:

http://www.google.com, View My Google
http://www.github.com, View My Github

```
ul>li*>a[title=$#]{$#}
```

creates

```
<ul>
   <li><a href="http://www.google.com, View My Google">http://www.google.com, View My Google</a></li>
   <li><a href="http://www.github.com, View My Github">http://www.github.com, View My Github</a></li>
</ul>
```

Where as if you add support for multiple output positions, something could be created like:

```
ul>li*>a[title=$#1]{$#2}
```

creates

```
<ul>
   <li><a href="http://www.google.com">View My Google</a></li>
   <li><a href="View My Github">View My Github</a></li>
</ul>
```
##

**Comment by sergeche** [comment]
This features is out of Emmet scope, there are better ways to achieve such result
