### ISSUE TITLE
Tag generation does not work when using two or more lorem generators without using parenthesis.

### ISSUE THREAD

**Issue by scifisamurai** [emmetio/emmet#306]
.row>lorem5>.subRow>lorem3 does not work
but 
.row>(lorem5)>.subRow>lorem3 does.

I've tested the above in the 3rd party vim plugin (https://github.com/mattn/emmet-vim) as well as the supported sublime text plugin in version 2.0.2 x64.  Both were tested on Ubuntu Linux 12.04 64bit.
##

**Comment by sergeche** [comment]
Works fine in recent version
