### ISSUE TITLE
incorrect expansion for $ followed by number. eg:- li{$00}*3

### ISSUE THREAD

**Issue by cosmosgenius** [emmetio/emmet#307]
The expansion of li{$00}*3 should produce

``` html
<li>100</li>
<li>200</li>
<li>300</li>
```

Instead it is empty ie.

``` html
<li></li>
<li></li>
<li></li>
```

if one more $ is added it works fine ie li{$$00}*3 gives

``` html
<li>0100</li>
<li>0200</li>
<li>0300</li>
```
##

**Comment by sergeche** [comment]
Happend due to `$N` was parsed as tabstop, not as `$` and `00`. In recent version this should work since only `${N}` syntax is supported
