### ISSUE TITLE
Add support for "c$color" to "color: $color;"

### ISSUE THREAD

**Issue by jhned** [emmetio/emmet#309]
Writing "c#fff" expands to "color: #fff;", but say I'm using SASS or LESS and have color variables to deal with.

In that case, having "c$color" expand to "color: $color;" or "bgc$color" expand to "background-color: $color;" would save me a whole lot of time. 

I'd write it myself, but I'm not really sure how that component of Emmet works. So count it as an enhancement request.
##

**Comment by sergeche** [comment]
Works in recent Emmet versions
