### ISSUE TITLE
snippets for Markdown ?

### ISSUE THREAD

**Issue by raphaelgoetter** [emmetio/emmet#317]
Hi,

I would like to create snippets for my markdown files (links, images, etc) but I did not find any documentation for different formats of HTML, CSS.

I modified the `snippets.json` file and added : 

```
"md": {
        "filters": "html",
        "snippets": {
            "image": "![alt](/path/ 'title'')"
        }
    },
```

... but nothing happens.

Is it possible to create this kind of snippets?
##

**Comment by yahyazini** [comment]
+1
