### ISSUE TITLE
Emmet HTML script tag expansion issue?

### ISSUE THREAD

**Issue by ilanbiala** [emmetio/emmet#320]
When I type `script[src="/source/here"]` and press tab, the src attribute is not created. It just creates a `<script></script>` tag opening and closing. Any thoughts on this?

**Comment by falafflepotatoe** [comment]
its possible its coming from the endless loop detect error @ abbreviation.js:566

im getting similar problems here

maybe it was caused by the lodash removal

also expandabbreviation('!') doesnt do anything i thought it was the html5 cmd -- but maybe thats just for sublime and im using the npm

**Comment by fbm-static** [comment]
why has this been closed?

**Comment by willow9886** [comment]
Expanding html tags doesn't seem to be working properly for me. I'm using a fresh install of both Atom and Emmet. 

For example, when I expand ! or html:5,  I just get <!></!> or <html:5></html:5> , instead of 

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <title>Document</title>
</head>
<body>
    
</body>
</html>

Same thing happens when I expand any of the other html tags. It simply results in creating whatever I type in open and closed brackets.

Anybody know how I can get html tags to expand properly?

**Comment by falafflepotatoe** [comment]
@willow9886  i fixed that by upgraded my emmet (and node? i dont remember) versions ;d... also an older ver of emmet (i think i used .17 or .13) worked also for me

**Comment by JaveMejia** [comment]
i write, script and type ctrl+space.

Ready.

**Comment by GuitarHero1969** [comment]
> why has this been closed?

**Comment by sergeche** [comment]
This issue is not related to Emmet itself, it may be related to a plugin for a specific editor.

**Comment by GuitarHero1969** [comment]
The issue exists in VS Code 1.45.1 aswell.

How do you custom edit the HTML boilerplate that Emmet generates when typing exclamation mark ?

Is this possible ?

**Comment by sergeche** [comment]
See https://code.visualstudio.com/docs/editor/emmet

**Comment by GuitarHero1969** [comment]
> See https://code.visualstudio.com/docs/editor/emmet

Nothing works, - already tried.

I want Emmet to insert <script type='text/javascript' src=''></script> when I type script in the file editor. 
Why is this so difficult ???

**Comment by sergeche** [comment]
Can you describe steps you made? You can type `script[type="text/javascript" src]` to get the expected result

**Comment by GuitarHero1969** [comment]
I started typing script into the head section of the boilerplate generated by ! but the Emmet Abbreviation doesn't follow what is in my snippets.json file. 
The only options are <script> and <script:src>
Your suggestion doesn't work!

{
  "html": {
	"snippets": {
		"script": "script[type='text/javascript' src]"
	} 
  }
}

**Comment by sergeche** [comment]
Where did you put this JSON? Did you set document syntax to HTML?

**Comment by sergeche** [comment]
This one works for me
<img width="1099" alt="image" src="https://user-images.githubusercontent.com/93595/83633774-27dc6500-a5aa-11ea-8bbb-a8cb2228722a.png">

**Comment by GuitarHero1969** [comment]
It is in a local folder that is set to same as emmet.extensionsPath in settings.json

**Comment by GuitarHero1969** [comment]
Managed to resolve.
Adding an extra entry in ..AppData | Roaming | Code | User | snippets | html.json seems to be the answer.
Which begs the question what is the emmet.extensionsPath used for in settings.json ?

**Comment by sergeche** [comment]
It’s a path to folder with Emmet config and extensions: https://docs.emmet.io/customization/
Note that in future versions Emmet configs will be cloud-based with UI for editing them

**Comment by GuitarHero1969** [comment]
(To prevent others wasting a whole day of development time)
In ..AppData | Roaming | Code | User | snippets | html.json:

{
	// Place your snippets for html here. Each snippet is defined under a snippet name and has a prefix, body and 
	// description. The prefix is what is used to trigger the snippet and the body will be expanded and inserted. Possible variables are:
	// $1, $2 for tab stops, $0 for the final cursor position, and ${1:label}, ${2:another} for placeholders. Placeholders with the 
	// same ids are connected.
	// Example:
	// "Print to console": {
	// 	"prefix": "log",
	// 	"body": [
	// 		"console.log('$1');",
	// 		"$2"
	// 	],
	// 	"description": "Log output to console"
	// }

	"": {
		"prefix": "script:all",
		"body": "<script src='${1}' type='text/javascript'></script>"
		}	
}

The option will show as "User Snippet" in the drop-down when you start typing (not "Emmet Abbreviation")

**Comment by sergeche** [comment]
This is how you create native VSCode snippet, not Emmet abbreviation. E.g. you won’t be able to modify it with custom attributes in runtime or chain with other snippets

**Comment by GuitarHero1969** [comment]
I don't understand the difference ! Anyway, this achieves what Ilan biala was asking!
