### ISSUE TITLE
Ruby1.9-style hashes for Haml

### ISSUE THREAD

**Issue by rusty-key** [emmetio/emmet#327]
there is no option in preferences to switch [haml hash styles](http://haml.info/docs/yardoc/file.REFERENCE.html#ruby_19style_hashes)

default: `%a{:href => "#"}`
1.9: `%a{href: "#"}`
##

**Comment by jonathansimmons** [comment]
It looks to me that this would only require one change [here](https://github.com/emmetio/emmet/blob/3a946a2ca2c4b0e5878547dab9911e04edc1bd64/lib/filter/haml.js#L58)

```json
  return attr.name + ': ' + value
```

I'm not yet familiar with Sublime text enough to rebuild the package and test this. Can anyone help us out here? 

CC: @sergeche

**Comment by sergeche** [comment]
Newest Emmet implementation outputs attributes as `%a(href="#")`.
You can propose another (configurable) syntax like this: https://github.com/emmetio/emmet/blob/master/src/markup/format/haml.ts
