### ISSUE TITLE
Trouble emmet with notepad++

### ISSUE THREAD

**Issue by cedenoaugusto** [emmetio/emmet#330]
When I tried use Emmet, I got a message box. Title: Exception. Message: Unknow. Then another message box, Title: Emmet, message: python script plugin did not accept the script.

Notepad++: 6.6.7 
OS: Win 7
##

**Comment by beefmaster** [comment]
My install works fine, i have windows 7 (64bit). I have pycharm installed and the developer kit installed for python so that might have something to do with it.
