### ISSUE TITLE
Class always first attribute

### ISSUE THREAD

**Issue by katrinkerber** [emmetio/emmet#331]
When assigning a class to an element I always want that to be the first attribute to show. 

With some elements, other attributes will always be prepended

For example:
`a.test`
gets expanded to 
`<a href="" class="test"></a>`

or

`input.test`
gets expanded to 
`<input type="text" class="test">`

Is there a way to change this so the class is always first?
##

**Comment by singihae** [comment]
I really wonder.
Please tell us how to do that.

I Want
```
a.test[href=#]
```
gets  expaned to 
```
<a class="test" href="#"></a>
```

or

```
div.test#testId[title=this is test]
```
gets expanded to
```
<div class="test" id="testId" title="this is test"></div>
```

Is there a way to change class is always first and id is always second?

**Comment by nigel-riss** [comment]
+ 1

**Comment by apallbox** [comment]
+1 

Now layouts are mostly BEM or something similar based so CSS class names are important such a class names in programming languages. There is definitely must be a way to put classes first or even set attributes order globally to keep code consistence.

**Comment by justafrontender** [comment]
+1

**Comment by randomnf** [comment]
+1

**Comment by Eugeno** [comment]
also waiting

**Comment by sergeche** [comment]
Moving to separated issue for new codebase: https://github.com/emmetio/expand-abbreviation/issues/16
