### ISSUE TITLE
<script type="text/javascript" src=""></script>

### ISSUE THREAD

**Issue by una** [emmetio/emmet#341]
It would be really nice to have a shortcut (i.e. just typing `script:js`) to produce this:

`<script type="text/javascript" src=""></script>`

with the cursor inside of src. I just find myself writing this a lot.

Again, its a nice-to-have :)

**Comment by sergeche** [comment]
There’s `script:src` snippet already for this. Also, try implied attributes: http://emmet.io/blog/beta-v1-1/

**Comment by bruceontheloose** [comment]
Also @una, in case you didn't know, you can omit `type="text/javascript"` in HTML5 pages (i.e., those with `<!DOCTYPE html>`, as I imagine you're aware). Emmet will omit it for you using the shorthand @sergeche mentioned.

**Comment by una** [comment]
:+1:  `script:src` is what I was looking for, sorry! :)
