### ISSUE TITLE
|t (trim) filter does not remove number markers inside custom attributes

### ISSUE THREAD

**Issue by hegivor** [emmetio/emmet#35]
Performing this abbreviation ol>li*>span{$#}+{ }+a[title=$#]{$#}|t on the following:
1. list item one
2. list item two
3. list item three

produces this output:

&lt;ol&gt;
    &lt;li&gt;
        &lt;span&gt;list item one&lt;/span&gt; 
        &lt;a href="" title="1. list item one"&gt;list item one&lt;/a&gt;
    &lt;/li&gt;
    &lt;li&gt;
        &lt;span&gt;list item two&lt;/span&gt; 
        &lt;a href="" title="2. list item two"&gt;list item two&lt;/a&gt;
    &lt;/li&gt;
    &lt;li&gt;
        &lt;span&gt;list item three&lt;/span&gt; 
        &lt;a href="" title="3. list item three"&gt;list item three&lt;/a&gt;
    &lt;/li&gt;
&lt;/ol&gt;

Note that the |t (trim) filter did not remove the number marker inside the custom title attribute [].
##

**Comment by Rafiozoo** [comment]
First of all, thank you for your great idea and support!
I would be delighted with another filter. Let's call it "**h**", which could do some kind of serialization. I can't explain expertly, please imagine as below.
**Input**:
```
1. Ajánlat
2. Az ügyfeleink
3. Rólunk
4. Kapcsolatba lépni
```
**Wrapping Abbreviation**:
`ul>.[$#]|h|t*>a[/$#]|h|t{$#}|t`

**Output**:
```
<ul>
	<li class="ajanlat"><a href="/ajanlat">Ajánlat</a></li>
	<li class="az-ugyfeleink"><a href="/az-ugyfeleink">Az ügyfeleink</a></li>
	<li class="rolunk"><a href="/rolunk">Rólunk</a></li>
	<li class="kapcsolatba-lepni"><a href="/kapcsolatba-lepni">Kapcsolatba lépni</a></li>
</ul>
```

**Comment by sergeche** [comment]
No more filters in upcoming Emmet implementation, it’s up to editor plugin implementation to remove any list markers
