### ISSUE TITLE
Add flex abbreviations

### ISSUE THREAD

**Issue by bikbah** [emmetio/emmet#353]
Add abbreviations for `flex` layout.
`display: flex;`
`flex: 1;`
`flex-flow;`
`flex-direction;` etc.
http://css-tricks.com/snippets/css/a-guide-to-flexbox/

**Comment by Xaviju** [comment]
:+1: +1

**Comment by FireCoding** [comment]
:+1: +1 pretty please

**Comment by FireCoding** [comment]
"fx" would be a great namespace, i.e.,
fx = flex: |;
fxd:c = flex-direction:column;
etc...

**Comment by sergeche** [comment]
Everyone can contribute new abbreviations: just hit “Fork” button and update https://github.com/emmetio/emmet/blob/master/lib/snippets.json

**Comment by FireCoding** [comment]
Thank you, pull request submitted

**Comment by ThiRaBrTNK** [comment]
`fx1-1-a` expands to 'flex: 1px 1px auto;'. I suppose this doesn't make sense? I suppose `flex: 1 1 auto;` would be right output.
