### ISSUE TITLE
"wrap with abbreviation" adds backslash (\) before dollar sign($)

### ISSUE THREAD

**Issue by tylik1** [emmetio/emmet#354]
Emmet 1.0.1.3 Netbeans 8.0.1. When I use "wrap with abbreviation" shortcut, all dollar signs inside this block are prepended with backslashes. So $ becomes \$. 
Really need this fix as  I use xslt templating engine where Dollar signs are used for calling variables.
##

**Comment by Skoua** [comment]
Hey there.

I'm using Emmet 1.0.1 on TextMate and I'm still getting this bug.
Was it eventually fixed?

**Comment by sergeche** [comment]
Fixed in upcoming version
