### ISSUE TITLE
Brackets load error with Emmet

### ISSUE THREAD

**Issue by awakekat** [emmetio/emmet#355]
Just FYI, looks like you have your hands full:
![screen shot 2014-12-23 at 2 06 16 pm](https://cloud.githubusercontent.com/assets/5148843/5541880/483630e2-8aad-11e4-8256-c92e3b53b945.png)

**Comment by waldekcher** [comment]
Hi, sorry for bumping but I've got same problem and can't resolve it.. I got both updated and can't run working together.

**Comment by sergeche** [comment]
I was fixed long ago: https://github.com/emmetio/brackets-emmet/blob/master/prompt.js#L52
Make sure you’re using latest Emmet package
