### ISSUE TITLE
Typing CSS-like abbreviations has stopped auto-completeing

### ISSUE THREAD

**Issue by LL782** [emmetio/emmet#358]
The Emmet package in SublimeText3 had been working for me very nicely for me but at some point recently something has changed and I'm wondering what it might be.

Previously I would type `div.region>div.co>div.ci.c1` and the tab completion would give me: 
```
<div class="region">
	<div class="co">
		<div class="ci c1"></div>
	</div>
</div>
```
Now I get this unhappy result:
```
div.region>div.co>div.<ci class="c1"></ci>
```
Any thoughts?

**Comment by dingo-d** [comment]
Happened to me too. I used to write css snippets like bd+, and after hitting tab, I'd get 

<html>border: 1px solid #</html>

 but now nothing happens. When I put bd in css I get out border, but that's it.

**Comment by sergeche** [comment]
Check out ST console log for errors

**Comment by dingo-d** [comment]
I have this error

<pre>
Traceback (most recent call last):
  File "emmet-plugin in C:\Users\Acer 1\AppData\Roaming\Sublime Text 3\Installed Packages\Emmet.sublime-package", line 375, in run_action
  File "emmet-plugin in C:\Users\Acer 1\AppData\Roaming\Sublime Text 3\Installed Packages\Emmet.sublime-package", line 324, in _action
PyV8.JSError: JSError: ParseError: CSS parsing error at line 5, char 1: Unterminated string
}
^ ( emmet-app.js @ 10006 : 8 )  -> 		throw errObj;
</pre>

**Comment by sergeche** [comment]
It says your CSS is invalid

**Comment by dingo-d** [comment]
But it loads fine. The weird thing is that sometimes completion works, sometimes it doesn't. In the same file. I looked at the line 5 and it's just a text in the comment.

**Comment by sergeche** [comment]
Can you post your CSS here?

**Comment by dingo-d** [comment]
It's for work purposes, so I can't, sorry. I'll try to validate it via w3c services, see if there are some lines that are problematic. And I'll see if the Developer FF says something. Thanks for pointing me in the right direction :)

**Comment by dingo-d** [comment]
I validated my css and now it works. Weird because it worked before. Well I'm glad it got sorted out :) Thank you very much ^^

**Comment by LL782** [comment]
Just for the record, this issue appears to be fixed for me now too. I'm left wondering, was there an update that fixed this? 

Anyway, thanks!
