### ISSUE TITLE
Квадратные скобки в сниппетах

### ISSUE THREAD

**Issue by agrygoriev** [emmetio/emmet#362]
Привет!
При попытке сохранить в **Emmet.sublime-settings** сниппет с квадратными скобками ругается на ошибку.
Например вот так не работает:
`"bscarousel": ".carousel.slide#carousel-example>ol.carousel-indicators>li[data-target="#carousel-example" data-slide-to="0"]*3^.carousel-inner>.item.active>img+.carousel-caption"`

А вот так нормально:
`"bscarousel": ".carousel.slide#carousel-example>ol.carousel-indicators>li*3^.carousel-inner>.item.active>img+.carousel-caption"`
##

**Comment by sergeche** [comment]
Видимо, проблема была в том, что вместо аббревиатуры описывался элемент. В новой версии (готовится к выпуску) такой проблемы не будет
