### ISSUE TITLE
className support for react

### ISSUE THREAD

**Issue by konsumer** [emmetio/emmet#364]
I am using Emmet with [JSX](https://github.com/allanhortle/JSX) in Sublime Text 3.

It would make me so happy if `.container` expanded to `<div className="container"></div>` not `<div class="container"></div>`. Is there a good place to configure this behavior or override it in code?

In react JSX, they opted to use `className` rather than `class`, I guess because `class` is a javascript keyword and JSX is "XML-like in javascript". React used to support both, but now it only supports `className`.

I also put an issue over [here](https://github.com/allanhortle/JSX/issues/6) but this is probaby a more appropriate place to ask about this.
##

**Comment by NerdCowboy** [comment]
Here's a good workaround:
https://gist.github.com/max-mykhailenko/41d0c3991d92f38dcbc6

**Comment by konsumer** [comment]
Thank you! That looks really good.

**Comment by sergeche** [comment]
Actually, Emmet already supports JSX natively: https://twitter.com/emmetio/status/583398878789132289

**Comment by NerdCowboy** [comment]
Yup, I just found that out myself. :+1: It only expands with Ctrl+E natively though. I tried following the instructions on the link I posted to get it to expand with Tab and it doesn't seem to work unfortunately.

**Comment by sergeche** [comment]
https://github.com/sergeche/emmet-sublime#tab-key-handler

**Comment by thedaviddias** [comment]
@sergeche this issue is still relevant?

**Comment by sergeche** [comment]
No, it’s not relevant anymore

**Comment by thedaviddias** [comment]
@sergeche Can someone close it then?

**Comment by konsumer** [comment]
I'll do it! Totally using emett with JSX, like every day.
