### ISSUE TITLE
I want to generate Chinese characters just like lorem do

### ISSUE THREAD

**Issue by tennessine** [emmetio/emmet#367]
I want to know how.

What I did: 
1. mkdir -p ~/emmet
2. touch preferences.json / touch snippets.json / syntaxProfiles.json

What's next?
##

**Comment by w3hacker** [comment]
I put a lorem-zh.js file on ~/emmet, but it seems it doesn't be loaded.But the *.json works fine.Is it a bug?

**Comment by w3hacker** [comment]
I solved it myself.

**Comment by w3hacker** [comment]
想实现的人可以加我 qq: 389443626 只限sublime text 3+
