### ISSUE TITLE
What is "⌅" shortcut key?

### ISSUE THREAD

**Issue by s-ogawa-mediba** [emmetio/emmet#371]
Hi, nice to meet you.

I trying Emmet on Adobe Brackets.
But, I can't understand what "Expand Abbreviation" shortcut key.
My Mac not have "⌅" key. Where is "⌅" key?
Also, Why "⌅" key is assigned?

Best regards!

**Comment by bruceontheloose** [comment]
Hi, @s-ogawa-mediba,

I haven't used Brackets, but judging by https://github.com/emmetio/brackets-emmet/blob/master/keymap.json, it looks like Tab or Ctrl-Alt-Enter should expand abbreviations. You can change the key bindings in that file, too, if you'd like (see "Default keybindings" on https://github.com/emmetio/brackets-emmet).

Hope that helps,

Bruce

**Comment by s-ogawa-mediba** [comment]
Hi, @bruceontheloose 

OMG!  It was Enter key!!
Thank you for your answer!!

**Comment by bruceontheloose** [comment]
Hi, @s-ogawa-mediba,

You're welcome. Glad you figured it out!

- Bruce
