### ISSUE TITLE
 Tab completions have changed (Sublime Text 2)

### ISSUE THREAD

**Issue by eriksilver** [emmetio/emmet#373]
I've been using Emmet with Sublime Text 2 and my tab completions have changed and I'm not sure why.

    Where I used to enter: 'div' (tab) and get <div></div>; now I get 'display: block'
     'p' (tab) was <p></p>; now is 'padding: ;'
     'h1' (tab) was <h1></h1>; now is 'height: 1px;'

I'm not sure if this is a settings issue or something else?

**Comment by sergeche** [comment]
That's because your document syntax is set to CSS

**Comment by eriksilver** [comment]
It looks like the document syntax is html. Is there something I need to change in settings?

![code_notes_see_bookmark_fo _and_index_html_ _documents_ _first_playground_ _bloc-jams_and_railsfactory_and_tab_completions_have_changed__sublime_text_2__ _issue__373_ _emmetio_emmet](https://cloud.githubusercontent.com/assets/10926923/6337291/7af474c0-bb6e-11e4-8c7e-1d24cacb7be7.jpg)

**Comment by sergeche** [comment]
Your source code is broken because of invalid `<!-- ... -->` comment inside `<style>` element

**Comment by eriksilver** [comment]
Thanks, Sergey. That was it.
