### ISSUE TITLE
PSPAad 4.5.9 + Emmet throw 'Endless loop detected'

### ISSUE THREAD

**Issue by Fbo75** [emmetio/emmet#378]
Hi,
I've tried to use Emmet with PSPAD 4.5.9 (on WIN7 Pro)
and when I select "Expand Abbreviation"
The emmet script throws an exception at line 1843
throw 'Endless loop detected'.
I've no idea how to fix it.
Thanks for your help!
Regards
Francois
##

**Comment by sergeche** [comment]
PSPad plugin is not supported anymore
