### ISSUE TITLE
EJS incorrectly uses the JSX snippets

### ISSUE THREAD

**Issue by clayzermk1** [emmetio/emmet#382]
I use EJS templates. Up until recently, EJS has always just used the HTML snippets which worked fine for my purposes. Today, I expanded a simple div with a class "foo" (`div.foo`) and instead of `class="foo"` in the element, I saw `className="foo"`.

Digging around, I saw that some of the most recent changes are to support JSX which uses the `className` attribute.

Since there isn't an EJS snippet, I'm assuming it's somehow getting picked up as JSX.

Any help would be much appreciated. I am more than happy to help debug/etc. Thank you!

Note: I'm using emmet-atom.
##

**Comment by ivansf** [comment]
Having the same issue, did you find a way to fix it?

**Comment by clayzermk1** [comment]
Sadly, I uninstalled Emmet since Atom has tag snippets anyway.

**Comment by skyrpex** [comment]
I also want to expand to class instead of className (I use Vue JSX files).

Can anyone point how to alter the expansion? Thanks.

**Comment by sergeche** [comment]
In upcoming v2, this feature will be controlled via preferences for each syntax individually
