### ISSUE TITLE
Expanding HTML tags in Atom

### ISSUE THREAD

**Issue by willow9886** [emmetio/emmet#383]
Expanding html tags doesn't seem to be working properly for me. I'm using a fresh install of Atom and Emmet. 

For example, when I expand `!` or `html:5`,  I just get `<!></!>` or `<html:5></html:5>` , instead of 

    <!DOCTYPE html>
    <html lang="en">
    <head>
    <meta charset="UTF-8" />
    <title>Document</title>
    </head>
    <body>
    
    </body>
    </html>

Same thing happens when I expand any of the other html tags. Anybody know how I can get html tags to expand properly?

**Comment by mamoyko** [comment]
type "! then tab"

**Comment by carc1n0gen** [comment]
I think I am having a related issue while expanding ANYTHING.  It was working fund, I closed the editor, the next day I opened it up and expanding was no longer working.

`ul>li*6` then I press tab (also tried ctr+e)

When pressing tab, it just inserts a tab.  When pressing ctr+e I get a "Replace in current buffer" dialog at the bottom of the editor.

**Comment by sergeche** [comment]
Check out DevTools for possible errors

**Comment by sergeche** [comment]
Also you can open Keybinding Resolver and check if Emmet action is matched for Tab key

**Comment by carc1n0gen** [comment]
I just realized that my issue is that I'm working on a php page now, before I tested in plain html page.

**Comment by sergeche** [comment]
https://github.com/emmetio/emmet-atom#tab-key
