### ISSUE TITLE
Sublime text: in color the "#" is removed after ;

### ISSUE THREAD

**Issue by beshur** [emmetio/emmet#390]
Hi!.

In Sublime text, when I expand the color property with the actual hex-color in my clipboard, it is expanded with that color (`c` -> tab -> `color: #2dadea`).
And when I put it semicolon after that, the "#" is removed from color.

Very subtle thing.

**Comment by sergeche** [comment]
Looks like you are using Hayaku for this thing

**Comment by beshur** [comment]
oops, sorry )
