### ISSUE TITLE
ReSharper Plugin prevents tabbing from working

### ISSUE THREAD

**Issue by phillip-haydon** [emmetio/emmet#392]
I'm not sure where to raise this issue. Sorry if it's the wrong place.

I'm using the Emmet for ReSharper plugin, it's works GREAT, but it breaks tabbing for Live Templates in other languages like C#.

**Comment by sergeche** [comment]
You should fill issue in ReSharper tracker. ReSharper uses its own Emmet implementation so I can’t help you with this

**Comment by phillip-haydon** [comment]
Ahh ok, they link directly to you so wasn't sure where to post.
