### ISSUE TITLE
input name = name attribute just returns name

### ISSUE THREAD

**Issue by leem32** [emmetio/emmet#397]
Its quite common for me to use **name="name"** for a form input field, but if i use emmet to do this like: `input[name=name]` this completes to be `<input type="text" name>` when it obviously should be `<input type="text" name="name">`
##

**Comment by sanspace** [comment]
I've just tried this in cloud9 editor (c9.io)

    input[name=hello]
    input[name=name]

yields respectively

    <input type="text" name="hello">
    <input type="text" name="name">

So, it seems to work fine on c9. How about your editor? Can you provide more details?

**Comment by wangyueg** [comment]
Me too, i write input[name=name] in sublime text 3, but it shows <input type="text" name>.

**Comment by sergeche** [comment]
Should be fixed in v2
