### ISSUE TITLE
`display: flex` Vendor Prefixes Undefined

### ISSUE THREAD

**Issue by MethodGrab** [emmetio/emmet#401]
Atom 1.0.19 / emmet-atom 2.3.13

In Atom (and Sublime Text), if i try to expand `df` or `d:f` with `"css.autoInsertVendorPrefixes": true` then it prepends `undefined` to the start of each line:

![image](https://cloud.githubusercontent.com/assets/2421069/10190230/10b7e046-6763-11e5-92c3-5f7d9ccb0e6c.png)
![image](https://cloud.githubusercontent.com/assets/2421069/10190236/1a4f3a96-6763-11e5-808d-f941f4d34f11.png)

I assume it's trying to prefix the `display` property as well as the value but that prefix isn't set.

Other flex properties, like `fxf` (`flex-flow`) expand correctly.
##

**Comment by sergeche** [comment]
Fixed in v2 (no more vendor prefixes)
