### ISSUE TITLE
lg() doesnt produces moz vendor 

### ISSUE THREAD

**Issue by adico-twistit** [emmetio/emmet#402]
lg() doesnt produces moz vendor 
sublime text 2 - windows 7

e.g.
lg(left,#fc0,30%,red)
background-image: -webkit-linear-gradient(left, #fc0, 30%, red);
background-image: -o-linear-gradient(left, #fc0, 30%, red);
background-image: linear-gradient(to right, #fc0, 30%, black);
##

**Comment by gugol2** [comment]
I have witnessed the same with:

- sublime text 3
- windows 7

**Comment by sergeche** [comment]
Fixed in v2 (no more vendor prefixes in output)
