### ISSUE TITLE
Перестал работать tab в sublime text 3 в jade

### ISSUE THREAD

**Issue by delch** [emmetio/emmet#406]
После установки jade snippets для SB3 перестал работать таб. Через ctrl+E работает, через tab нет. Перерыл все конфиги, никаких изменений не нашел. Как вернуть tab ?

**Comment by sergeche** [comment]
https://github.com/sergeche/emmet-sublime#how-to-expand-abbreviations-with-tab-in-other-syntaxes

**Comment by delch** [comment]
В jade всё равно не работает. В html всё ок.

**Comment by sergeche** [comment]
Значит надо смотреть плагин jade snippets, что он там добавил и как переопределил обработку Tab

**Comment by delch** [comment]
В нём только файлы сниппетов и readme.md, больше в репо никаких файлов.

**Comment by sergeche** [comment]
https://github.com/sergeche/emmet-sublime/blob/master/Preferences.sublime-settings#L29

**Comment by delch** [comment]
В общем ничего не помогает.

**Comment by delch** [comment]
Проблема видимо в обновлении jade для st3 https://github.com/davidrios/jade-tmbundle/issues/58

**Comment by sergeche** [comment]
Судя по всему, проблема в том, что теперь синтаксис Jade определяется как `text.jade`, а не `source.jade`: https://github.com/davidrios/jade-tmbundle/blob/master/Syntaxes/Jade.JSON-tmLanguage#L635

Собственно, решается изменением/добавлением операнда на Tab: https://github.com/sergeche/emmet-sublime/blob/master/Default%20(OSX).sublime-keymap#L377

**Comment by delch** [comment]
Спасибо, Сергей, всё заработало!

**Comment by Terramaster777** [comment]
мне помогло с табом описанное выше решение, но теперь почему то emmet по табу вставляет html http://joxi.ru/DrlaB97uLPMlmP :( как с этим бороться?

**Comment by sergeche** [comment]
Запушил исправление, должно работать

**Comment by xiansheng** [comment]
Не помогло

**Comment by Terramaster777** [comment]
нет, до сих пор в jade вставляется html http://joxi.ru/gmvRl96fk91Wma =(

**Comment by le-genda** [comment]
не работает

**Comment by AleksandrChukhray** [comment]
Подскажите, где найти выше перечисленные файлы?

 https://github.com/sergeche/emmet-sublime/blob/master/Default%20(OSX).sublime-keymap#L377

**Comment by strobox** [comment]
+1. Abbreviation expands to html in jade files now.

**Comment by sergeche** [comment]
Запушил обновление, должно работать с последней версией Jade

**Comment by Terramaster777** [comment]
ура! спасибо большое, теперь всё снова работает как и прежде) меня за эти два дня уже тошнит от atom

**Comment by strobox** [comment]
Works now! Thanks very much.

**Comment by kru1980** [comment]
Здравствуйте уважаемые. Для новичков объясните алгоритм решения проблемы. Куда зайти и что поправить.
