### ISSUE TITLE
Abbreviation for self-closing tags in jsx

### ISSUE THREAD

**Issue by deathmood** [emmetio/emmet#413]
Is it possible to expand a word into self-closing tag? I saw smth similar here https://github.com/smihica/emmet-mode#empty-tags it should work like

`AppComponet/ -> <AppComponent />`

but that does not work with emmet.
Sorry for writing it here, but I could not find anything about this in documentation.
##

**Comment by jmk2142** [comment]
Did you find a solution for this? In the same boat.

**Comment by sergeche** [comment]
It requires custom resolver for JSX so upper-cased abbreviations can be resolved to empty tags.

**Comment by jmk2142** [comment]
Roger. That's the key word I was looking for. Found some of your other posts regarding how to go about building one. Thanks!

**Comment by deathmood** [comment]
The simplest solution is to use default shortcuts:

`Component`   --->  `ctrl+e` or `tab` ------> `<Component></Component>` ------>  `ctrl+shift+ ~` ---> `<Component />`

**Comment by brumm** [comment]
@deathmood could you elaborate on this?

`ctrl+shift+ ~` has no effect here (using atom) and there's no built-in command that turns a closing tag pair into a self-closing one.

**Comment by deathmood** [comment]
@brumm it is a `split/join tag` action http://docs.emmet.io/actions/split-join-tag/ . That works in sublime.

**Comment by rockallite** [comment]
On Sublime 3 for Mac, the default hotkey for `split/join tag` is `Command + Shift + '` (single quote)

**Comment by ignaciopicun** [comment]
In atom you can do `Command + Shift + j`

**Comment by mpolichette** [comment]
I use emmet for writing JSX and it would be really cool if emmet would let use cycle through the forms.
E.G. repeatedly hitting `ctrl+e` would cycle as such:
`MyComponent` -> `<MyComponent></MyComponent>` -> `<MyComponent />` -> `MyComponent`

I think this would make it really simple to learn/discover the feature also.

I'm not sure if this belongs in the emmet repo or the atom plugin repo, I've cross posted this in https://github.com/emmetio/emmet-atom/issues/408

**Comment by eromoe** [comment]
How about vscode ??   `ctrl+e`  and `ctrl+shift+ ~` both not work

**Comment by deathmood** [comment]
Yes, now I'm also working in vscode (for about a year now) and there is no shortcut there

**Comment by dziamid** [comment]
Webstorm has this already `AppComponet/` `TAB` => `<AppComponent />`

**Comment by IamManchanda** [comment]
For VS Code also 

`hello-world/` `TAB` => `<hello-world>`
so I have to write `/` by myself but works :)

**Comment by nishitmehta1** [comment]
Search for Split/Join in Keyboard Shortcuts. You'll see an Emmet option. YOu can set it to any key you prefer.

**Comment by sergeche** [comment]
Upcoming v2 support `elem/` syntax to output self-closing elements

**Comment by shahmir811** [comment]
> For VS Code also
> 
> `hello-world/` `TAB` => `<hello-world>`
> so I have to write `/` by myself but works :)

That works, awesome

**Comment by ccrsxx** [comment]
If you're using VS Code put this inside your setting.json.

```
  "emmet.syntaxProfiles": {
    "html": {
      "self_closing_tag": true
    }
  }
```

`AppComponent/` `ENTER` => `<AppComponent />`

**Comment by ozgrozer** [comment]
I'm using Emmet's "Split/Join Tag" feature in Sublime Text 4 and it helps a lot.

For those who want use it go to `Preferences/Key Bindings` in Sublime.
Then paste the code below and change the shortcut key however you want.

```json
[
  {
    "keys": ["super+shift+a"],
    "command": "emmet_split_join_tag"
  }
]
```

Before
`<Component` tab `<Component></Component>` delete closing `<Component>` add slash `<Component />`

Now
`<Component` tab `<Component></Component>` cmd+shift+a `<Component />`

**Comment by lizy-Leeeeee** [comment]
> Webstorm has this already `AppComponet/` `TAB` => `<AppComponent />`

Vscode 1.85.1 work fine!
