### ISSUE TITLE
Support  "k" output bracket({})

### ISSUE THREAD

**Issue by yisibl** [emmetio/emmet#415]
CSS at present all the specifications are not in the beginning of the K property, so we can quickly through the k output a pair of curly braces.

input:

``` css
.foo k
```

<kbd>tab</kbd> output:

``` css
.foo {

}
```
##

**Comment by yisibl** [comment]
Don't have this plan?

**Comment by sergeche** [comment]
You can add `k` snippet which expands to `{}` in any modern editor as native snippet. Or you can add it as custom Emmet snippet
