### ISSUE TITLE
Можно избавиться от символа "пробел"?

### ISSUE THREAD

**Issue by DimaelVertigo** [emmetio/emmet#416]
При выполнении 
bb1-s-#5e5e5e
на выходе получаем border-bottom: 1px solid8[ . . ]#5e5e5e; 
[. .] - два символа пробел вместо одного

**Comment by sergeche** [comment]
Пока, как вариант, писать `bb1-s#5e5e5e`. Потом исправлю

**Comment by DimaelVertigo** [comment]
Так тоже удобно, благодарю.
