### ISSUE TITLE
line-height единицы по уполчанию.

### ISSUE THREAD

**Issue by DimaelVertigo** [emmetio/emmet#417]
При выполнении lh16, получаем line-height: 16;
Если не добавить вручную px, то получим значение без каких-либо единиц. Можно ли задать единицы px по по умолчанию, как для других единиц?

**Comment by sergeche** [comment]
http://docs.emmet.io/customization/preferences/
Свойство css.unitlessProperties

**Comment by DimaelVertigo** [comment]
Спасибо.
