### ISSUE TITLE
Update ! html expansion with something a bit more modern

### ISSUE THREAD

**Issue by corysimmons** [emmetio/emmet#419]
```html
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title></title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>
  <body>

  </body>
</html>
```

This is straight from H5BP (really smart people who debate this stuff all day). It doesn't include opinionated stuff like if the user wants to use a stylesheet or if they want to include jQuery or Google Analytics, but it does set up a boilerplate that works well on all devices.

**Comment by BuKinoshita** [comment]
:+1:

**Comment by corysimmons** [comment]
Thanks for the PR @BuKinoshita
