### ISSUE TITLE
Remove alt from img expansion

### ISSUE THREAD

**Issue by corysimmons** [emmetio/emmet#421]
In fact, remove everything but the very basis from every abbreviation.

`img[tab]` should expand to `<img src="">`

**Comment by BuKinoshita** [comment]
Why?

**Comment by corysimmons** [comment]
I was thinking that it shouldn't be there if an image is decorative (has no relevance to content whatsoever) but I guess [W3C recommends](https://www.w3.org/wiki/HTML/Elements/img#Requirements_for_providing_text_to_act_as_an_alternative_for_images) you provide an empty `alt=""` tag for anything that doesn't have alt info.

Ugh. I get the importance of alt text, but an empty tag looks so stupid. Good job forcing rules down our throat for our own good, W3C.
