### ISSUE TITLE
BEM: Block inside another block?

### ISSUE THREAD

**Issue by igoradamenko** [emmetio/emmet#428]
Hello.

I'm not sure about right behavior, but when I write abbeviation like this:

    .news(.title.-title(.-text))

I expect to get html like this:

```
<div class="news">
	<div class="title news__title">
		<div class="title__text"></div>
	</div>
</div>
```
I expect it because there is one of the rules [here](http://docs.emmet.io/filters/bem/):

> if you start class name element prefix, filter will resolve block name from parent node;

But I get this:

```
<div class="news">
	<div class="title news__title">
		<div class="news__text"></div>
	</div>
</div>
```

Am I wrong? Why does the element inside the block `title` resolve like `news__text`?

**Comment by sergeche** [comment]
Because parent element contains `news` block name (`.news__title`) so `.-text` is resolved like `.news__text`

**Comment by igoradamenko** [comment]
It looks strange. Do I understand correctly that if node has `.block1` and `.block2__elem` classes then for child node block name will be resolved like `.block2`? And is it possible to use block inside another block with [mix](https://en.bem.info/method/key-concepts/#mix)? As far as I understand it's possible only if we mix one-node block (without child elements; i. e. like `.link` but not like `.list` with `.list__elem` inside).

**Comment by sergeche** [comment]
> It looks strange. Do I understand correctly that if node has .block1 and .block2__elem classes then for child node block name will be resolved like .block2?

Yes. Since there are two possible block names on the same element Emmet doesn’t know which name you want to use for child element so it uses the last one.

You can use multiple `-` prefixes to reach parent block element you need.

**Comment by igoradamenko** [comment]
Okay, but multiple `-`'s aren't the solution in this issue, right?

~~I can't understand why Emmet can't resolve it correctly.~~ OK. While I've been writing the answer I've looked at the code of BEM filter and found out why it can't resolve. 

Let's imagine that we have structure like this:

```
.block1
|__ .block1__elem1
|__ .block1__elem2
|__ .block1__elem3.block2
|_____ (*)
```

We need to resolve block name for node `(*)`. It seems obiviously that if parent element has N classes where one of them is the block-classname then `(*)` is element of this block. Else `(*)` is an element of `block1` inside `block2` and it's in contradiction to BEM.

Right now BEM filter can't resolve it because this filter rewrite `__bem.block` property on `item` when it already has this property.

I'm not sure absolutely, but let me show you my tests. At first let's expand my example from OP of this issue agan:

    .news(.title.-title(.-text))

Right HTML (as I said before) is:

```
<div class="news">
    <div class="title news__title">
        <div class="title__text"></div>
    </div>
</div>
```
But when Emmet resolves block name of 2nd node (`.title.news__title`) at first it detects that node has `.title` class and assigns `item.__bem.block` a value equals `title`, then it detect that node has `.news__title` class and **reassigns** `item.__bem.block`.. and sets it value to `news`.

So when Emmet resolves block name of 3nd node, it checks parent node and gets its block name, i. e. `news`.

I think that solution of this problem is condition around [L154 of bem.js](https://github.com/emmetio/emmet/blob/1cb7e8101b9885d27f86a5cf13ade3a23b99c5b4/lib/filter/bem.js#L154):

```
if (!item.__bem.block) {
    item.__bem.block = block;
}
```

Maybe it needs more quality solution, but it works. For example let's expand this big abbreviation:

    .main(.-news-reviews(.news.-news(.title.-title(.-text)+.news-carousel(.-wrapper(.-item(.date.-date(.-day+.-month))*2)+.-nav_left+.-nav_right))))

Right now Emmet + BEM filter expand it to:

```
<div class="main">
	<div class="main__news-reviews">
		<div class="news main__news">
			<div class="title main__title"> <!-- fail -->
				<div class="main__text"></div> <!-- fail -->
			</div>
			<div class="news-carousel">
				<div class="news-carousel__wrapper">
					<div class="news-carousel__item">
						<div class="date news-carousel__date"> <!-- fail -->
							<div class="news-carousel__day"></div> <!-- fail -->
							<div class="news-carousel__month"></div> <!-- fail -->
						</div>
					</div>
					<div class="news-carousel__item">
						<div class="date news-carousel__date"> <!-- fail -->
							<div class="news-carousel__day"></div> <!-- fail -->
							<div class="news-carousel__month"></div> <!-- fail -->
						</div>
					</div>
				</div>
				<div class="news-carousel__nav news-carousel__nav_left"></div>
				<div class="news-carousel__nav news-carousel__nav_right"></div>
			</div>
		</div>
	</div>
</div>
```

But if we add condition about that line, expandtion will be correctly:

```
<div class="main">
	<div class="main__news-reviews">
		<div class="news main__news">
			<div class="title news__title">
				<div class="title__text"></div>
			</div>
			<div class="news-carousel">
				<div class="news-carousel__wrapper">
					<div class="news-carousel__item">
						<div class="date news-carousel__date">
							<div class="date__day"></div>
							<div class="date__month"></div>
						</div>
					</div>
					<div class="news-carousel__item">
						<div class="date news-carousel__date">
							<div class="date__day"></div>
							<div class="date__month"></div>
						</div>
					</div>
				</div>
				<div class="news-carousel__nav news-carousel__nav_left"></div>
				<div class="news-carousel__nav news-carousel__nav_right"></div>
			</div>
		</div>
	</div>
</div>
```

I hope I'm not mistaken.
