### ISSUE TITLE
Counter Base doesn't start at 0

### ISSUE THREAD

**Issue by mrmcpowned** [emmetio/emmet#430]
doing `$@0` simply starts the base at 1 instead of 0.

**Comment by igoradamenko** [comment]
It starts at 0 for me. 
Where do you use Emmet?
 
![emmet](https://cloud.githubusercontent.com/assets/6537798/13378147/9447f238-de0b-11e5-93ca-e670cefad118.gif)

**Comment by mrmcpowned** [comment]
I use PHPStorm, though I'm not sure what version of Emmet it uses
![image](http://i.imgur.com/9cwz8mf.gif)

**Comment by igoradamenko** [comment]
I'm not sure about PHPStorm, but counter base was added on 5 feb 2015 by [6b5eb68](https://github.com/emmetio/emmet/commit/6b5eb68b726a781a5b99377aa711ae445cb4b820). 

Try to use another base like `$@1`, `$@5`, etc. If it does not work it seems like you have out of date version of Emmet :)

**Comment by sergeche** [comment]
PHPStorm uses its own implementation of Emmet so you should address this issue to PHPStorm devs

**Comment by mrmcpowned** [comment]
@sergeche Thanks for that, I'll address that to the PHPStorm devs
