### ISSUE TITLE
Support for SugarSS

### ISSUE THREAD

**Issue by corysimmons** [emmetio/emmet#434]
This is PostCSS' new/official alternative to preprocessor syntaxes: https://github.com/postcss/sugarss

**Comment by mugukamil** [comment]
It puts semicolons on the end...

**Comment by corysimmons** [comment]
Are you using Stylus syntax or did Emmet officially start supporting this?

**Comment by mugukamil** [comment]
@corysimmons Did u use this plugin? [https://github.com/hudochenkov/Syntax-highlighting-for-PostCSS](url)
I extracted this package and in file [https://github.com/hudochenkov/Syntax-highlighting-for-PostCSS/blob/master/Syntaxes/SugarSS.tmLanguage](url)
I changed 414 line from ```source.css.postcss.sugarss``` to ```source.sss```

I extracted Emmet package. Then modified some lines in file editor.js

on 382 line if statement going 
```
else if (/\b(less|scss|sass|css|stylus|postcss)\b/.test(scope)) {
		// detect CSS-like syntaxes independently,
		// since it may cause collisions with some highlighters
		syntax = RegExp.$1;

		if (syntax === 'postcss') {
			syntax = 'css';
		} else if (syntax === 'sss') { // I added this 3 lines started from else
			syntax = 'sass'; // this
		} // and this
```

and now its expand m0 how margin: 0 (without semicolon).

but without this changes its expand margin: 0;

**Comment by corysimmons** [comment]
Thanks for workaround

**Comment by sergeche** [comment]
Available in v2
