### ISSUE TITLE
Feature request: Expand regexp to random string

### ISSUE THREAD

**Issue by krnlde** [emmetio/emmet#435]
Hey guys. I really enjoy the `lorem20` feature in emmet and would like to ask for a similar enhancement. I see the necessity for a random regular expression expander in emmet, for lighning fast mock data. There is a library out there which does the regexp trick already: https://github.com/fent/randexp.js

Some example usecases would be:
* Dates: `/[01][0-9]\.[01][0-9]\.(19|20)\d\d/ -> 19.07.2060`
* Keys: `/[A-Z0-9]{4}-[A-Z0-9]{4}-[A-Z0-9]{4}-[A-Z0-9]{4}/ -> 76X8-PMCW-SY8S-XY42`
* ZIPs: `/[1-9][0-9]{4}/ -> 75417`

Maybe it could be integrated with the emmet expansion. What do you think?

**Comment by krnlde** [comment]
Bump. If there's no interest I'll close this.

**Comment by sergeche** [comment]
This is out of Emmet scope. It’s better to create a separate plugin for this

**Comment by krnlde** [comment]
I'm not confident with emmet and its plugin structure. Is the "lorem" thingy also a separate plugin?

Closing this.

**Comment by sergeche** [comment]
`lorem` is a part of Emmet and its syntax and ease of use perfectly fits Emmet. RandExp requires different syntax and I hardly believe someone would write `/[01][0-9]\.[01][0-9]\.(19|20)\d\d/` just to get `19.07.2060`

**Comment by krnlde** [comment]
I think it's worth the hustle to copy-paste the regexp from google to achieve this awesome strip:

`table>(thead>(tr>th>{Name})+(tr>th>{Date}))+(tbody>tr*200>(td>lorem2)+(td>/[01][0-9]\.[01][0-9]\.(19|20)\d\d/))+tfoot>tr>td[colspan=2]>{Footnotes}`
