### ISSUE TITLE
Add the ability to enter fake names and data similar to lorem

### ISSUE THREAD

**Issue by ksteigerwald** [emmetio/emmet#442]
It would be nice to have the ability to add fake first, last and email addresses similar to the Faker Gem in ruby. I have found a plugin sketch that does something similar and have found it particularly useful in many occasions.

**Comment by sergeche** [comment]
This feature looks too large for core Emmet package. The new implementation allows custom processing of expanded abbreviation so this feature should be implemented as separate module
