### ISSUE TITLE
Support BEM option for deep name nesting?

### ISSUE THREAD

**Issue by paulozoom** [emmetio/emmet#445]
Right now, this: 

```
.a>.__b>.__c
```

expands to

```
<div class="a">
    <div class="a__b">
        <div class="a__c"></div>
    </div>
</div>
```

But shouldn't the deepest element’s class be `a__b__c` instead? Would it make sense to add support for this option?

**Comment by randomnf** [comment]
Look at Yandex's BEMMET. May be it will help you.

**Comment by sergeche** [comment]
Please re-open this issue if it’s still relevant
