### ISSUE TITLE
Cannot change settings in sublime-project

### ISSUE THREAD

**Issue by joedski** [emmetio/emmet#447]
I am either running into an unsupported feature or cannot figure out the proper way to do this.
### Expected

Putting the following into `ProjectName.sublime-project` would change the settings of the HTML syntax profile to use single quotes even though the default is double quotes.

``` json
{
    "folders": [
        {
            "path": "ProjectName"
        }
    ],
    "Emmet": {
        "syntaxProfiles": {
            "html": {
                "attr_quotes": "single"
            }
        }
    }
}
```

Then, entering the following in an HTML file...

```
foo.bar
```

and expanding it with `Ctrl + E` would result in

``` html
<foo class='bar'></foo>
```
### Result

Entering the above in a new file with the Syntax set to HTML and expanding with <key>Ctrl+E</key> results in the following instead.

``` html
<foo class="bar"></foo>
```
### Other Use Cases

Many VDOM implementations, Deku for example, do not use `className` or `htmlFor`, instead opting just to use `class` and `for` respectively.  While an extra setting in the `jsx` syntax profile would be nice, this can also be solved simply by setting `jsx`'s `filters` to `["html"]`.  However, this is an issue if you are switching between Deku projects and React projects since you would need to constantly add and remove this `filters` setting.

Additionally, when using the StandardJS syntax style, the default JSX settings run afoul of the "single quoted strings except when avoiding escaping" rule.

Reading configuration from a project's settings file would alleviate this by allowing per-project settings like

``` json
{
    "folders": [
        {
            "path": "path/to/NonReactVDOMProject"
        }
    ],
    "Emmet": {
        "syntaxProfiles": {
            "jsx": {
                "attr_quotes": "single",
                "filters": [ "html" ]
            }
        }
    }
}
```

This would as an example allow expansion of `foo.bar` into `<foo class='bar'></foo>` instead of `<foo className="bar"></foo>` for a particular project, even one using StandardJS styling, while leaving things alone for React based projects.

**Comment by sergeche** [comment]
Thanks for detailed issue :) Currently, Emmet doesn’t support per project settings, only global. This might be fixed in future releases. There could be possible workaround/fix to update Emmet preferences before each action run but it may lead to unexpected results in non-project files and possible performance degradation

**Comment by joedski** [comment]
Thanks for the response!  That does sound like a troublesome workaround, alas, especially given the number of non-project folders I tend to have open.  I suppose I'll just just either put up with errors in StandardJS based projects for now, or use something like [hyperx](https://www.npmjs.com/package/hyperx) in my personal projects.

**Comment by sergeche** [comment]
This feature can be configured in v2: https://github.com/emmetio/emmet/tree/v2
