### ISSUE TITLE
Not add comments after li,a,span and other "short" tags

### ISSUE THREAD

**Issue by BlizzzArt** [emmetio/emmet#448]
Я нашёл похожую тему: https://github.com/sergeche/emmet-sublime/issues/225
Но я не смог подключить файлы с настройками .json 
Я их создал здесь C:\Users\Eugen.WebStorm2016.1\config\plugins, но они никак не влияют
возможно ли сделать такое в WebStorm ?

**Comment by BlizzzArt** [comment]
Поставил Atom и сделал все нужные настройки, и атом по умолчанию делает то что не было в шторме.

**Comment by sergeche** [comment]
Видимо, проблема в реализации для WebStorm (всё ещё актуально?)
