### ISSUE TITLE
Немного асинхронного API

### ISSUE THREAD

**Issue by mrmlnc** [emmetio/emmet#455]
Привет, @sergeche,

Так получилось, что я занимаюсь интеграцией Emmet в VS Code. Мы с Эрихом (глава проекта) испытываем проблемы с интеграцией в силу того, что нам хотелось бы сохранить асинхронность API работы с файлами и предоставить информацию об ошибках в удобном для пользователя виде, а не как это реализовано в ST (проблемы бегут в консоль) или Atom (бросает окошко необработанного исключения).

У нас есть несколько проблем:

  1. Функция `locateFile` синхронная и всегда возвращает строку, хотя в коде предусмотрен вариант обработки ошибки при `null`.
  2. Функция `createPath` возвращает коллбэк вместо строки, которая предусмотрена в коде. Это вызывает ошибку.
  3. Функция `save` сохраняет файл синхронно и не позволяет обработать ошибки.

Нам бы хотелось иметь возможность вернуть коллбэк в каждую функцию, связанную с работой с файлами.

Я готов выслать вам PR на озвученные в этом ишью проблемы. Было бы замечательно, если вы его приняли до середины июля, чтобы успеть в этот итерационный блок разработки редактора.

**Comment by sergeche** [comment]
Привет, да, конечно, высылай. Я там что-то правил под асинхронный код, но уже не помню, где и как оно используется.

PS: я через некоторое время собираюсь полностью переписать проект, там уже будут другого рода абстракции и более плотная интеграция с возможностями редакторов

**Comment by sergeche** [comment]
Кстати, может быть вам будет интересна ещё и эта штука? https://github.com/livestyle/atom#livestyle-analyzer

Я собираюсь запустить крауфандинговую для его доработки (как минимум анализ данных со всего проекта), возможно, пользователям VS Code такой инструмент также будет полезен :)

**Comment by mrmlnc** [comment]
@sergeche, думаю, можно написать плагин. Как раз недавно был добавлен API доя создания примечаний до и после текста.

**Comment by sergeche** [comment]
Если поддержите кампанию, то и я могу написать ;)

**Comment by mrmlnc** [comment]
@sergeche, на всякий случай скажу, что я никоим образом не отношусь к Microsoft :dancer: 

От себя помочь могу кодом/вкладом, когда посмотрю что это за штука такая :+1:

**Comment by sergeche** [comment]
Понял, спасибо 👍

**Comment by mrmlnc** [comment]
@sergeche, касательно вопрос по бесконечному циклу, который описан в ишью 453. Теоретически, можно просто добавить:

```js
while (c && c !== q)
```

Это решает проблему с циклом и тесты все проходит, но мало ли что.
