### ISSUE TITLE
Собранный модуль

### ISSUE THREAD

**Issue by mrmlnc** [emmetio/emmet#460]
Мы тут обсуждали вопрос обновления Emmet в VS Code (https://github.com/Microsoft/vscode/pull/9002#issuecomment-235187687) и Эрих заметил, что после обновления до 1.6.0 размер пакета вырос в 6 раз по количеству файлов и в 3 раза по размеру. Произошло это из-за вынесения `caniuse-db` в зависимости проекта.

Дело в том, что для редакторов, построенных на Electron и подобным ему (Brackets, Atom, VS Code), каждый мегабайт кода играет роль. Также стоит уточнить, что из `caniuse-db` у вас используется только один файл `caniuse-db/data.json`.

Кстати, собранный модуль сэкономил бы некоторое количество обращений к FS.

На текущий момент есть предложение создать отдельный пакет `emmet-built` с собранным и минифицированным Emmet, включая БД-файл.

Сложно сказать что-либо по этому поводу, потому что я не вижу путей как держать БД актуальной.

P.S. Проще всего будет решить эту проблему на их стороне ;)

**Comment by sergeche** [comment]
Привет, да, видел обсуждение. Наверно, остаётся только ждать, когда я перепишу Emmet, ну или действительно сделать отдельный репозиторий, который будет собирать сам Emmet, но без CIU. Что-то подобное сейчас делается для CodeMirror-плагина по просьбе сайта CodePen: https://github.com/emmetio/codemirror/blob/webpack/emmet.js

**Comment by mrmlnc** [comment]
Ждём Emmet 2.0.0 ❤️
