### ISSUE TITLE
how to use emmet  in  node ?

### ISSUE THREAD

**Issue by fukai007** [emmetio/emmet#461]
Could you please kindly tell me how to use emmet  after it has been installed  by npm install emmet
Thanks!

**Comment by sergeche** [comment]
Basically, you can `require('emmet')` and then run `expandAbbreviation(abbr)` method to expand abbreviations. Do you have to deal with any specific tasks with Emmet?

**Comment by fukai007** [comment]
I am H5 lead and I am learning  nodeJS . I will try it . do you give to me a Some code  about  How use to  emmet in nodeJS  or  website

**Comment by fukai007** [comment]
I  run to code  but I don't know  it is right  ?
var emmet = require('emmet');


function ss() {
    var htmlString = emmet.expandAbbreviation("ul>li*5");
    console.log(htmlString);
}

console.log("start................");
ss();
console.log("end....................");

**Comment by sergeche** [comment]
yes, that’s right

**Comment by fukai007** [comment]
Sorry to border you again.According to your guidance,it runs as below:

```
start................

	
${0}

	
${0}

	
${0}

	
${0}

	
${0}


end....................
```
------------------------------
There are some questions still trouble me, could you please kindly give a hand to me?  

1、where is  api  for emmet ?
2、where is  demo ?
3、Can I custom emmet in nodeJS ?

Thanks a lot!

**Comment by au-phiware** [comment]
@fukai007 You need to be specific. What is your goal? You need to elaborate on "custom emmet in nodeJS"... that sentence doesn't really make sense.

Emmet is useful for creating an editor plugin, see the wiki for an example: https://github.com/emmetio/emmet/wiki/Plugin-How-To.

If you are looking for a small utility that converts a css selector into a html string/element take a look at [put-selector](https://www.npmjs.com/package/put-selector).

If you are satisfied or have moved on, it would be appropriate for you to close this issue.

**Comment by fukai007** [comment]
thank you
