### ISSUE TITLE
Installation failed when intalling Emmet manually on Brackets

### ISSUE THREAD

**Issue by marcossangon96** [emmetio/emmet#465]
Hi,
I'm trying to install Emmet on Brackets by dragging the zip and I'm getting the error "Installation Failed. The extension encountered an error while starting up".
Screenshot attached.

Btw, I've searched and tried lots of "answers" and no-one worked for me.

What to do?
![untitled](https://cloud.githubusercontent.com/assets/22070932/18505693/bf90b214-7a68-11e6-8899-2c5773a93e98.png)

**Comment by sergeche** [comment]
https://github.com/emmetio/brackets-emmet#readme
