### ISSUE TITLE
when I write inline CSS ，that has chinese in the same line

### ISSUE THREAD

**Issue by budapeisidajiudian** [emmetio/emmet#469]
as for me，emmet is a amazing tool which improving my developing efficiency.
but recently，when I write the code like this

``` html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>mynewproject</title>
  </head>
  <body style="pl">  
    <div style="pl">Emmet 很好</div>
    <script src="dist/build.js"></script>
  </body>
</html>
```

in the line 8,if there has chinese  in the same line，where you want to use the Emmet.
when I tap the 'tab',in Atom ,it will throw a Error like :

``` javascript
Uncaught ParseError: CSS parsing error at line 1, char 41: Unrecognized character '很' background-image:

Emmet 很好
; ----------------------------------------^
```

but in sublime ,it just a normal 'tab'.Emmet dosen't work any more.

**Comment by sergeche** [comment]
This happens when you put caret inside `style=""` attribute?

**Comment by budapeisidajiudian** [comment]
yes.
for some reason,in this project,we have to put caret inside style="" attribute.

**Comment by sergeche** [comment]
OK, will check it out

**Comment by sergeche** [comment]
Should be fixed in v2
