### ISSUE TITLE
Abbreviations for CSS value "inherit"

### ISSUE THREAD

**Issue by Golmote** [emmetio/emmet#474]
Hi!

Are there abbreviations that expand to the CSS value "inherit"? I couldn't find any tip in the docs and the fuzzy search doesn't seem to work here.

Some examples:
* `c:i` currently expands to `outline-color: invert;`, but it could expand to `color: inherit;`
* `ta:i` currently expands to `text-align: justify;`, but it could also expand to `text-align: inherit;`

(Or maybe `in` or `ih`, whichever seems more appropriate...)

It looks like the value `inherit` is not included in the possibilities at the moment.

**Comment by sergeche** [comment]
Use `-` instead of `:`. The `-i` is an explicit value separator: `c-i` → `color: inherit;`

**Comment by Golmote** [comment]
Thanks for the quick answer. This does not appear to work in my version on WebStorm, but if it's supposed to be the case, then the issue is not on this side.

**Comment by Golmote** [comment]
Ok, for those wondering, WebStorm currently supports it with a dot: `c.i` → `color: inherit;` ;)
