### ISSUE TITLE
how to  change  HTML To  emmet  expression

### ISSUE THREAD

**Issue by fukai007** [emmetio/emmet#478]
HI，Sergey Chikuyonok
  
  can you  help me  ? I  want to  change  HTMLString To emmet expression  in nodeJS  , for example
```
    var  x = '<ul><li>1</li><li>2</li></ul>'
    var emmetFlag =  xxxxxx(x); 
    console.log(emmetFlag) // ul>li*2
```

**Comment by sergeche** [comment]
Emmet doesn’t support this feature I there’s no plans to implement it
