### ISSUE TITLE
${child} issue

### ISSUE THREAD

**Issue by tomstock1337** [emmetio/emmet#480]
I'm attempting to specify where a child element should be inserted with the following code snippet:

   "z1col":"th.columns.first.last.small-12.large-12>table>tr>th{${child}}+(th.expander)",

When I use "z1col>p", the child elements are being inserted into the th.expander element, and not the previous th element. I've tried $1 and ${child} and neither appear to be working.

I am using Emmet in sublime

**Comment by sergeche** [comment]
The `${child}` token is used for snippets only, e.g. arbitrary code chunks. Emmet doesn’t support insertion targets for elements, it just inserts children into deepest child node
