### ISSUE TITLE
Emmet + Brackets + Where is Emmet's main.js?77

### ISSUE THREAD

**Issue by Scorpovi4** [emmetio/emmet#482]
Hi devteam, as i know, to make emmet work under brackets in *.pug files need to change emmet's main.js or rather add pug: require('./pug'), to filter object, so question, WHERE is emmet's main.js for brackets?

**Comment by Scorpovi4** [comment]
How to make emmet do what it do in pug file under brackets is here
https://github.com/emmetio/emmet/pull/450/commits/8c4632be475db016eaed942b272d54e98b2cb232
and all directories with requirement files is here
C:\Users\%User%\AppData\Roaming\Brackets\extensions\user\brackets-emmet\node_modules\emmet\

World's wide mystery why fixes is and under brackets it ain't integrated.

**Comment by kyurii** [comment]
thanks
