### ISSUE TITLE
Is it possible to automatically create a block with curly braces to help write CSS?

### ISSUE THREAD

**Issue by hendrasan** [emmetio/emmet#483]
I used Hayaku before, and they have a handy shortcut, `cmd+enter` to create a block with curly braces already written down.

So if I type `.selector` then press `cmd+enter`, it will create

```
.selector {
  
}
```

with the cursor put between the curly braces.

I know it's minor, but it's really handy. Is it possible in Emmet?

**Comment by sergeche** [comment]
Not related to Emmet, should be considered as editor-specific feature
