### ISSUE TITLE
Automatically adding vendor prefixes when "css.autoInsertVendorPrefixes" is "false"

### ISSUE THREAD

**Issue by dslpp056193** [emmetio/emmet#486]
These prefixes were added when:

```
{
    "caniuse.enabled": true,
    "css.autoInsertVendorPrefixes": false
}
```

But they were added only from caniuse data base.

Example.
If i use `df`, when `autoInsertVendorPrefixes` is `true`:
```
    display: -webkit-flex;
    display: -moz-flex;
    display: -ms-flex;
    display: -o-flex;
    -webkit-display: flex;
    -moz-display: flex;
    -ms-display: flex;
    -o-display: flex;
    display: flex;
```
And if i use `df`, when `autoInsertVendorPrefixes` is `false`:
```
    display: -webkit-flex;
    display: -moz-flex;
    display: -ms-flex;
    display: -o-flex;
    display: flex;
```

I think it's a bug

**Comment by albrin** [comment]
What kind of Code Editors or IDEs do you use?

**Comment by dslpp056193** [comment]
I use Visual Studio Code

**Comment by albrin** [comment]
@dslpp056193, please, try — https://github.com/emmetio/emmet/issues/499#issuecomment-305756962
It works for me.
