### ISSUE TITLE
How to cut long abbreviation line into two or maore short lines in emmet.vim?

### ISSUE THREAD

**Issue by yufeiluo** [emmetio/emmet#488]
<form action="">
        <p>
            <input type="" name="" size="" value="">
            <p>
                <input type="" name="" size="">
                <p>
                    <input type="" name="" value="">
                    <input type="" name="" value="">
                    <input type="" name="" value="">
                </p>
            </p>
        </p>
    </form>

The long line statement in emmet.vim abbreviation form can produce above html snippet structure quickly pressing <kbd>ctrl</kbd><kbd>y</kbd><kbd>,</kbd>.    

    form>(p>input[type="" name="" size="" value="" ]+p>input[type="" name="" size=""]+p>input[type="" name="" value="" ]*3)  

It's so long.    

[![enter image description here][1]][1]

I want to cut it into two lines.    

[![enter image description here][2]][2]

What i get is the following format to press  <kbd>ctrl</kbd><kbd>y</kbd><kbd>,</kbd>.

[![enter image description here][3]][3]

How to get the whole html snippet structure at the beginning when to cut the long emmet abbreviation into two parts?

  [1]: https://i.stack.imgur.com/LPHan.png
  [2]: https://i.stack.imgur.com/qKfwq.png
  [3]: https://i.stack.imgur.com/a0kLC.png

**Comment by sergeche** [comment]
Writing large abbreviations is anti-pattern, just write a few smaller and simple abbreviations
