### ISSUE TITLE
How to create the following  html structure?

### ISSUE THREAD

**Issue by yufeiluo** [emmetio/emmet#489]
Here is the target i want to create.

`<p>gender:<input type="radio" name="sex" value="male">male</p>`
`p{gender:}>input[type="radio" name="sex" value="male"]`
can create 
`<p>gender:<input type="radio" name="sex" value="male"></p>`
`p{gender:}>input[type="radio" name="sex" value="male"]{male}`
can't do the job too.    
How to add **male** after input?

**Comment by vadrudnev** [comment]
Hey try this 
p>{gender:}+input[type="radio" name="sex" value="male"]+{male}
Here is a cheat sheet also

https://docs.emmet.io/cheat-sheet/

**Comment by Anshuman-Verma** [comment]
Thanks for the cheat-sheat @vadrudnev , I was stuck on the same problem and surprisingly found this issue  fir the exact problem I had and it helped me real good, i hope this issue can be closed now.
