### ISSUE TITLE
Please update snippets.json

### ISSUE THREAD

**Issue by freMea** [emmetio/emmet#490]
Hi,

I think this default file could be improved to enhance the user experience.

In CSS section, add HSL support:

    "c:h": "color:hsl(${1:0}, ${2:100}%, ${3:50}%);",
    "c:ha": "color:hsla(${1:0}, ${2:100}%, ${3:50}%, ${4:1});",
    
    "tsh:h": "text-shadow:${1:h} ${2:v} ${3:blur} hsl(${4:0}, ${5:100}%, ${6:50}%);",
    "tsh:ha": "text-shadow:${1:h} ${2:v} ${3:blur} hsla(${4:0}, ${5:100}%, ${6:50}%, ${7:1});",
    
    "bxsh:h": "box-shadow:${1:inset }${2:hoff} ${3:voff} ${4:blur} ${5:spread }hsl(${6:0}, ${7:100}%, ${8:50}%);",
    "bxsh:ha": "box-shadow:${1:inset }${2:h} ${3:v} ${4:blur} ${5:spread }hsla(${6:0}, ${7:100}%, ${8:50}%, ${9:1});",

and so on for background properties.

**Comment by Anshuman-Verma** [comment]
This seems to be a valuable improvement, i hope project maintainers get to this asap. :+1:

**Comment by sergeche** [comment]
You can create PR with suggested snippets to https://github.com/emmetio/emmet/tree/v2/snippets
Or you can always customize Emmet with your own snippets
