### ISSUE TITLE
Some functions doesn't seem to work

### ISSUE THREAD

**Issue by Cronnay** [emmetio/emmet#495]
I have been trying to write something like: `div#createpost>ul>li*5` and it doesnt work.
Heck, even something simple like `div#createpost` doesnt work either. Is it a common bug?
Emmet was installed through packages inside Atom, but I removed it and installed it with NPM instead, and it doesn't work. 
Any tips what I can do?

apm v1.15.3
npm v.3.10.5

**Comment by sergeche** [comment]
Make sure document syntax is set to HTML
