### ISSUE TITLE
Question: “Lorem Ipsum” generator and Grouping

### ISSUE THREAD

**Issue by albrin** [emmetio/emmet#496]
How to correctly use “Lorem Ipsum” generator for grouped elements?
```
dl>(dt>lorem3+dd>lorem3)*2
```
I receive
```
<dl>
    <dt>Lorem ipsum dolor.
        <dd>Lorem ipsum dolor.</dd>
    </dt>
    <dt>Sapiente tempore, natus.
        <dd>Assumenda quibusdam, id!</dd>
    </dt>
</dl>
```
I expect to receive
```
<dl>
    <dt>Itaque, exercitationem fuga.</dt>
    <dd>Lorem ipsum dolor.</dd>
    <dt>Odio, enim, vero.</dt>
    <dd>Praesentium, suscipit temporibus.</dd>
</dl>
```

**Environment:**
Visual Studio Code 1.11.2

**Comment by hannesfrank** [comment]
The sibling operator `+` binds stronger than/takes precendence over the child  operator `>`, so you have to group at least the first child operator, like

```
dl>((dt>lorem3)+dd>lorem3)*2
```

which results in

```
    <dl>
        <dt>Lorem ipsum dolor.</dt>
        <dd>Lorem ipsum dolor.</dd>
        <dt>Cumque, voluptatibus, deleniti?</dt>
        <dd>At, ut fugiat.</dd>
    </dl>
```

**Comment by sergeche** [comment]
The `>` operator changes element context so you have to either use `^` operator to climb up the tree (`dl>(dt>lorem3^dd>lorem3)*2`) or use grouping as @hannesfrank suggests
