### ISSUE TITLE
Can I disable autoprefixer ?

### ISSUE THREAD

**Issue by MarvinXu** [emmetio/emmet#499]
for example, when I type 'bxb', it creates
```css
  -webkit-box-sizing: border-box
  -moz-box-sizing: border-box
  -ms-box-sizing: border-box
  box-sizing: border-box
```
but nowadays we have webpack do such thing. So is there a switch to turn off autoprefixer?

**Comment by albrin** [comment]
If you are using a Visual Studio Code, added the setting to the settings.json (user or workspace settings).
```
{
    "emmet.preferences": {
        "css.autoInsertVendorPrefixes": false
    }
}
```

> **css.autoInsertVendorPrefixes**
Automatically generate vendor-prefixed copies of expanded CSS property. By default, Emmet will generate vendor-prefixed properties only when you put dash before abbreviation (e.g. -bxsh). With this option enabled, you don’t need dashes before abbreviations: Emmet will produce vendor-prefixed properties for you.

https://docs.emmet.io/customization/preferences/

In other IDEs or Code Editors you can try to create a settings file (preferences.json) in the root directory of the project. More information you can find on the link — https://docs.emmet.io/customization/preferences/

**Comment by MarvinXu** [comment]
@albrin thx a lot!

**Comment by grantand** [comment]
@albrin, подскажите, может вы знаете как отключить префиксы но уже в брекетсе?

**Comment by chrisnajman** [comment]
To get rid of auto prefixes in Sublime Text click on Preferences > Package Settings > Emmet > Settings - User and add the following snippet :

```
{
	"preferences": {
		"css.autoInsertVendorPrefixes": false
	},
}
```

**Comment by GoOz** [comment]
Hi there, I have a weird issue related to this with Sublime Text.

I did the change in the User settings
```
{
  "preferences": {
    "css.autoInsertVendorPrefixes": false
  }
}
```
And it kinda works. When i type `d:f` it doesn't add the vendor prefixes but I type `df` it adds them. I don't know if it's related to the fuzzy search or what but it's bugging I think.
![emmetvendorprefixes](https://user-images.githubusercontent.com/1280069/40710886-24032192-63fa-11e8-8128-ab3255454ae2.gif)

**Comment by KitCarver** [comment]
I had the same issue in Sublime Text.
It works for me
`{
	"preferences": {
		"css.autoInsertVendorPrefixes": false,
		"caniuse.enabled": false
	},
}`

**Comment by GoOz** [comment]
@KitCarver My hero!
Do you know, by any chance, where does that `caniuse` option come from?

**Comment by KitCarver** [comment]
Yes, I found it here: [https://docs.emmet.io/customization/preferences/](https://docs.emmet.io/customization/preferences/)
> caniuse.enabled
> Enable support of Can I Use database. When enabled, CSS abbreviation resolver will look at Can I Use database first before detecting CSS properties that should be resolved

**Comment by sergeche** [comment]
Automatic prefixes are removed in Emmet v2

**Comment by T04435** [comment]
For IntelliJ users just disable `Auto insert css vendor prefixes` under:

`Preferences > Emmet > CSS`

![image](https://user-images.githubusercontent.com/10654469/91244124-e5808980-e78e-11ea-8173-ebd63573c6d4.png)
