### ISSUE TITLE
Symbol '$' becomes '1'

### ISSUE THREAD

**Issue by torzuoliH** [emmetio/emmet#500]
### `$` issue
When I try to use Emmet with a `$`, I don't get it in result.

#### Example
__Entry__

```
div[ng-repeat="x in y track by $index"]
```

__Expected__
```HTML
<div ng-repeat="x in y track by $index"></div>
```

__Result__
```HTML
<div ng-repeat="x in y track by 1index"></div>
```

I illustrate this issue with an Angular example, but it does the same anywhere.

**Comment by torzuoliH** [comment]
Found it was because of the `Item numbering: $`, but how can I pass this rule just for AngularJS syntax ?

**Comment by sergeche** [comment]
Right now, you have to escape `$`: `div[ng-repeat="x in y track by \$index"]`
It it fixed in new Emmet core

**Comment by torzuoliH** [comment]
Perfect ! Thanks 👌
