### ISSUE TITLE
How to add link tag in expanding html:5?

### ISSUE THREAD

**Issue by yufeiluo** [emmetio/emmet#504]
html:5 will be expanded as following.

```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
        
</body>
</html>
```

I want to customize it as following when to expand html:5 in my vim.

```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
    <link  href="" >
</head>
<body>
        
</body>
</html>
```

Here is my try .
vim snippets.json
#to change the line containing doc": as

> `doc": "html>(head>meta[charset=${charset}]+meta:vp+meta:edge+link[href=\"\"])+body",`

Why still no link tag when to expand html:5?

**Comment by sergeche** [comment]
Seems like a bug in Vim implementation, which was developed by third-party author
