### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by zel777** [emmetio/emmet#505]
I have been using TEA for Coda and I love the "Wrap Selected Lines In Tag" feature, but I see that emmet doesn't offer this. I can only wrap 1 line with an abbreviation. Is there a way you can incorporate the functionality to wrap multiple lines (each line) with a tag (abbreviation)?

**Comment by sergeche** [comment]
This feature already exists, Wrap with abbreviation

**Comment by zel777** [comment]
I see that, and it works great on a single line, but what about multiple lines? For example if I have 40 list items, I would have to select each line individually and wrap each one. What I'd like to see is that if I select multiple lines, that when I "Wrap with abbreviation" it wraps each line individually, not the whole selection.

**Comment by sergeche** [comment]
https://docs.emmet.io/actions/wrap-with-abbreviation/

**Comment by zel777** [comment]
Awesome! I didn't notice that you could use an asterisk to do that. Thanks sergeche!
