### ISSUE TITLE
Custom Expand Abbreviation

### ISSUE THREAD

**Issue by Bernardoow** [emmetio/emmet#507]
Hi !

I want change the result of expand abbreviation.

If I type div * 3, will be generate `<div></div> <div></div> <div></div>.`

I want if I type div *3 generate `div [ ] [ ], div [ ] [ ], div [ ] [ ].`

`div > p - > <div> <p> </p> </div>`

`div > p -> div [ ] [p [ ] [ ] ]`

My intetion, change` <div> to div [] [  and </div> to ] [].`

**Comment by sergeche** [comment]
it requires custom output formatter, see https://github.com/emmetio/markup-formatters as reference

**Comment by Bernardoow** [comment]
@sergeche Thanks sergeche! And Thanks for emmet sublime this is veeeeerry goood !!
