### ISSUE TITLE
CLI и REPL

### ISSUE THREAD

**Issue by D1mon** [emmetio/emmet#508]
Для программ которые не поддерживают emmet. Можно сделать консольную версию emmet. Пример использования:
`echo "ul>li*5>a" | emmet-cli`

и выведет развернутую запись
или так:
emmet-cli < file.txt
и др. способы (потоки ввода, вывода, ошибок).

> -i interactive (REPL)

emmet-cli -i
`> nav>ul>li`
выведет развернутую запись

**Comment by sergeche** [comment]
Проще использовать сайт, где можно развернуть любую аббревиатуру в редакторе: https://emmet.io
Технически, сделать CLI достаточно легко из новой ветки `v2`, там только движок для парсинга и обработки аббревиатур
