### ISSUE TITLE
Add support for Latte in Sublime Text

### ISSUE THREAD

**Issue by mikerockett** [emmetio/emmet#511]
Please can you add support for Nette Latte in Sublime Text? I rely on Emmet for my day-to-day, and have just switched from Twig to Latte for template rendering. Thank you! 👍

**Comment by lucker14** [comment]
Only 3 upvotes? That's hard to belive...

**Comment by sergeche** [comment]
Check out plugin README: http://github.com/sergeche/emmet-sublime
