### ISSUE TITLE
How to enable all kinds of file for emmet to edit?

### ISSUE THREAD

**Issue by hwypengsir** [emmetio/emmet#513]
To enable html,css,php in emmet.

    vim  .vimrc
    let g:user_emmet_install_global = 0
    autocmd FileType html,css,php EmmetInstall

How to enable all kinds of file for emmet to edit?
It is no use to set as :

    let g:user_emmet_install_global = 1

**Comment by sergeche** [comment]
This issue relates to Vim plugin which was developed by third-party author
