### ISSUE TITLE
when requiring emmet in node.js it errors

### ISSUE THREAD

**Issue by lifeiscontent** [emmetio/emmet#514]
when using webpack:

Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

code sample:

``` js
import emmet from 'emmet';
import 'emmet/bundles/snippets';
import 'emmet/bundles/caniuse';

export default emmet;
```

**Comment by GGGGino** [comment]
The same for me, when i use emmet with webpack it gives me:
`WARNING in ./node_modules/emmet/lib/emmet.js
3:27-34 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted`

**Comment by sergeche** [comment]
You should use new module instead: https://www.npmjs.com/package/@emmetio/expand-abbreviation

**Comment by GGGGino** [comment]
It works, thank you

**Comment by JFFby** [comment]
Hi, i have the same issue when I trying to add emmet for [react-ace](https://github.com/securingsincity/react-ace)
