### ISSUE TITLE
Bug: tab expanding HTML inside HTML attributes

### ISSUE THREAD

**Issue by blunket** [emmetio/emmet#515]
Oftentimes I encounter a bug where Emmet tries to expand an abbreviation inside an HTML attribute.

I'm using Sublime. Preview:

![emmetbugpreview](https://user-images.githubusercontent.com/17580512/31392790-c168bb8e-ad9f-11e7-9f11-2cd343d5bdc3.gif)

If it helps: this does not happen inside `href` or `src` or most other attributes. Also not limited to `img` tags nor limited to `alt` attributes. It has also happened in hyperlink `title` attributes for example.

**Comment by jdfm** [comment]
Can you show this happening in other editors? 

I just tried it in VSCode 1.22.2 and what you described did not happen there.

**Comment by blunket** [comment]
@jdfm You're right - I just installed VSCode and tried it, it doesn't happen.

However, it still happens in Sublime Text 3 (latest dev build).

**Comment by blunket** [comment]
Ah.. You're right. I didn't realize emmet-sublime was its own project. That's a shame because it seems like a dead project.

Maybe I'll check it out and make a PR there or something. Thanks.
