### ISSUE TITLE
Doesn't work with webpack import

### ISSUE THREAD

**Issue by Duskfall** [emmetio/emmet#516]
Steps to reproduce
Import emmet like this in a js file

`import 'emmet';` or if you want the object `import emmet from 'emmet';`

Expected result:
Emmet should be imported normally.

Actual result:
Webpack breaks when trying to load module
````
if (typeof module === 'object' && typeof define !== 'function') {
	var define = function (factory) {
		module.exports = factory(require, exports, module);
	};
}
````

**Comment by sergeche** [comment]
You should use https://github.com/emmetio/expand-abbreviation instead. This repo is obsolete

**Comment by Duskfall** [comment]
I have already tried https://github.com/emmetio/expand-abbreviation but it doesn't work with ace editor, probably because the 'ace/ext/emmet' is  using the old emmet right?
