### ISSUE TITLE
Everytime I type `wid` and hit TAB it autocompletes to `widow` instead of `width`

### ISSUE THREAD

**Issue by dsomel21** [emmetio/emmet#517]
A  couple of guys at work were chit chatting about things we hate about Sublime and as a joke I mentioned how much I despise the fact that when I type `wid` my css, it autocompletes  to `widow` and how much of a negative impact it had.

As a result, EVERYONE else had this issue too. And we found out it wasn't Sublime, it was emmet. One guy super cheesed and removed Emmet. The rest of us are still using it, but don't know  what to do... So I decided to open this issue.

**Comment by bruceontheloose** [comment]
Hi, @dsomel21,

To get `width`, use just `w`. You might find this handy if you haven't seen it before: [https://docs.emmet.io/cheat-sheet/](https://docs.emmet.io/cheat-sheet/).

And in case you didn't know, you can also do things like `w20` to get `width: 20px` (`px` is the default if a unit isn't specified) and `w25%` to get `width: 25%`.

- Bruce

**Comment by dsomel21** [comment]
My coworkers are gonna be so jealous! Okay, I guess this issue can be closed, I am just  so used to hitting `wid` + `TAB` but it's going to take some getting  used,
