### ISSUE TITLE
Feature Request: Add Bootstrap support

### ISSUE THREAD

**Issue by BitYog** [emmetio/emmet#519]
While coding a web page, I usually default to Bootstrap for layout and positioning. However, finding the proper CDN link takes me to the web and then I get distracted. It would be a whole lot better for me and my work, if I could just type 'bootstrap' in a HTML file, and Emmet expands that into this:

`<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">`

**Comment by sergeche** [comment]
You can customize Emmet with your own snippets, check out your editor plugin docs
