### ISSUE TITLE
Add support for CSS grid

### ISSUE THREAD

**Issue by PixelT** [emmetio/emmet#523]
https://css-tricks.com/snippets/css/complete-guide-grid/

**Comment by speiffer829** [comment]
I second that

**Comment by Willabee** [comment]
css-grid is widely used now.

**Comment by amishPro** [comment]
I agree. It would be very useful to add grid support right now.

**Comment by sergeche** [comment]
You can contribute snippets here: https://github.com/emmetio/snippets
