### ISSUE TITLE
Option to open void tag (opposite of force-close)

### ISSUE THREAD

**Issue by mantissa7** [emmetio/emmet#525]
I am using a component library that shares a case-insensitive reserved element `<col/>` as `<Col></Col>`, however emmet recognises this `Col` as a void tag and creates `<Col/>`.

Emmet has support for creating void tags using `/` but perhaps an inverted `\` tag to force a void tag to open would be nice? 

    Col  --> <Col/>
    Col/ --> <Col/>
    Col\ --> <Col><Col/>

I found the Split/Join functionality, however my IDEs (jetbrains) don't support this shortcut, and this might complement the force-void feature nicely.

**Comment by sergeche** [comment]
The ultimate solution is to create your own snippet as `col`. A better UI for updating snippets will be available in upcoming Emmet v2
