### ISSUE TITLE
why emmet killed zen code!!!

### ISSUE THREAD

**Issue by hakanelver** [emmetio/emmet#528]
i was surfing on youtube  and one of the turkish coder published a video about how zen code is great.. and i waste my time to test it. (cos it was looking usefull idea) But its not working with 64 bit notepad++ !  ok  download  and install 32 bit notepad++ but its not working again! year is 2018 and notepad  updated itself as v7.5.4... finally i got some imformation about zencode says at their webpage  the latest code script version was from 2011. and working with notepad++ juzt v0 version!!! https://code.google.com/archive/p/zen-coding/downloads
its unbelievable. are you kidding with people by take their time for notting? sure i dislike and send a feedback to this silly turkish coder. and i need to ask why emmet killed zencode? zencode could be better and handy. it could be helpfull for coders. why you did notting for 8 years about this great idea and now you keep sharing as you are working on it. 8 years!!! damn 8 years you did nottng for world IT and coders. anyway i m very regretfull to trust these web fakes again.

**Comment by sergeche** [comment]
Thanks for appreciating my efforts for building and supporting Emmet during all those years *for free*. I’m sorry I wasted your precious time by doing nothing for Notepad plugin, for you personally and whole IT industry: unfortunately, working on free and open-source doesn’t pay my bills and users like you believe that every open-source maintainer owe them.

As an act of my sincere apologies, I over two options for you:

1. Go fork yourself Emmet for Notepad++ plugin, make it work in recent Notepad plugin and make world IT industry happy again.
2. Try another editor like Sublime Text or VSCode and maybe world IT industry would have another chance.
