### ISSUE TITLE
Goto Matching Pair - not working

### ISSUE THREAD

**Issue by it6** [emmetio/emmet#529]
Thanks for this amazing plugin.

I use this along with `sublime text`, `Go to matching pair` doesn't work when attributes have `*`, `(`, `)`, `[`,  `]`, `$`. Which is common in the new angular.

For example the following markup
```
<schedule-info
  [shift]="request">
</schedule-info>
```

Please consider ignoring these `regex` characters when present as attributes so we can go to matching pair.

**Comment by sergeche** [comment]
Fixed in upcoming Emmet v2
