### ISSUE TITLE
Add support for more meta tags. 

### ISSUE THREAD

**Issue by the-thappy** [emmetio/emmet#532]
**Manifest**
`<link rel="manifest" href="/manifest.webmanifest">`
[Web App Manifest | MDN ](https://developer.mozilla.org/en-US/docs/Web/Manifest)
**Theme Color**
`<meta name="theme-color" content="#db5945">`
**Icon** (high-res favicons)
`<link rel="icon" sizes="192x192" href="nice-highres.png">`
(`link:favicon` somewhat does this, but converts to `<link rel="shortcut icon" type="image/x-icon" ... />`)
[Theme Color, Icon Tag | Google Developers](https://developers.google.com/web/updates/2014/11/Support-for-theme-color-in-Chrome-39-for-Android)

These tags directly correlate with **Progressive Web Apps** and support should be added to Emmet.

**Comment by sergeche** [comment]
You can add aPR with new tags into new version of `v2` branch, see https://github.com/emmetio/emmet/tree/v2/snippets
