### ISSUE TITLE
Can Emmet library be converted to an actual rendered library this would be so great for tempting in javascript

### ISSUE THREAD

**Issue by BreimerR** [emmetio/emmet#536]
`let a = new EmmetTemplateRenderer("ul>li*5");`

The produced result with jquery could be passed to give
And give the renderer access to the elements inside the provided string
`a.li,each(function(index){this.append(new EmmetTemplateRenderer("span.className#simple_list_item_${index}"))})`
`a = $(a);`
where now is equal
 `<ul><li></li><li></li><li></li><li></li><li></li></ul>`

**Comment by blunket** [comment]
There are many existing template rendering libraries for JavaScript already.

Check out this blog post https://www.creativebloq.com/web-design/templating-engines-9134396

**Comment by sergeche** [comment]
Agree with @blunket that there are better alternatives for templating. Although you can expand Emmet abbreviations on your web-site using most recent v2 version, see https://github.com/emmetio/emmet/tree/v2
