### ISSUE TITLE
Feature request: Tab stop.

### ISSUE THREAD

**Issue by ZerozAndOnes** [emmetio/emmet#542]
This feature might already exist, but I wasn't able to find it in the documentation or somewhere online.
If we have the following emmet: 
`(label+input.form-control)*3`
then it gets expanded to:

```
  <label for=""></label>
  <input type="text" class="form-control">
  <label for=""></label>
  <input type="text" class="form-control">
  <label for=""></label>
  <input type="text" class="form-control">
```
Now if we want to have a tab stop to specify the id of each input as a string (not just a number), then I don't think we currently have a solution for that. With the tab stop feature, we would then be able to specify the id for each of the input with the help of the tab stops. For instance, we might have something like
`(label+input.form-control#$!)*3`
Which will then be expanded to 
```
  <label for=""></label>
  <input type="text" id="_TabStop_" class="form-control">
  <label for=""></label>
  <input type="text" id="_TabStop_" class="form-control">
  <label for=""></label>
  <input type="text" id="_TabStop_" class="form-control">
```

**Comment by sergeche** [comment]
`(label+input[id].form-control)*3` should work

**Comment by ZerozAndOnes** [comment]
Thank you it does work, I overlooked trying that one out.
