### ISSUE TITLE
Can't Install extension for Brackets

### ISSUE THREAD

**Issue by Upal** [emmetio/emmet#543]
Hi, people recommended me Emmet but I failed to install the extension using Brackets "extension tool", I get this message (Win10)  : 

![fail](https://user-images.githubusercontent.com/2551324/46736296-fc9c5800-cc98-11e8-9bb0-83723df6ebff.png)

What do I have to do to solve this issue ? 

Thanks

**Comment by sergeche** [comment]
Looks like an issue with Brackets
