### ISSUE TITLE
Emmet in SublimeText3 not works with UTF-8

### ISSUE THREAD

**Issue by Curiouslynx** [emmetio/emmet#544]
Emmet in SublimeText3 doesn't works if document contains utf-8 symbols in `<pre>` tag.

Try using Emmet after:

`<pre>🔍</pre>`

**Comment by jluisgarcia** [comment]
That is probably an issue for Sublime Text repository. Not Emmet.

**Comment by sergeche** [comment]
Duplicate of #541
