### ISSUE TITLE
Emmet input checkbox & input radio (enhancement)

### ISSUE THREAD

**Issue by jluisgarcia** [emmetio/emmet#545]
For html input checkbox, Emmet currently outputs:
`<input type="checkbox" name="" id="">`
Is it possible to add the attribute "value"? This attribute is always used. The new output would be this:
`<input type="checkbox" name="" id="" value="">`
The same could be applied for input radio, which currently outputs:
 `<input type="radio" name="" id="">`
Thanks

**Comment by sergeche** [comment]
You can update default Emmet snippets as required. A new version will feature UI for updating snippets. Stay tuned!
