### ISSUE TITLE
completing CSS bg → background-color: with an extra # isn't practical

### ISSUE THREAD

**Issue by bjorn-ali-goransson** [emmetio/emmet#548]
When using emmet in VScode to complete the likes of "bg" in CSS, Less or SCSS we are provided with background-color: # in order to fill out the desired hex value.

But these days, it's far from certain that I want to input a hexadecimal value. Personally I prefer the literals `black` and `white` whenever they apply. We have CSS variables nowadays, and what about preprocessor variables from SCSS and Less?

Can't we remove it?

I guess we're talking about https://github.com/emmetio/snippets/blob/2e0618328ae9d28967bebd9144a369e014df704b/css.json#L62 and given all this, I am still not sure that this is the code affecting VScode behavior.

**Comment by bjorn-ali-goransson** [comment]
I think my PR solves this, not by removing the `#` but by making it easier to remove along with the suggested `000`

**Comment by sergeche** [comment]
Fixed in `v2` branch
