### ISSUE TITLE
Multiple classes expansion not working properly

### ISSUE THREAD

**Issue by wsjung** [emmetio/emmet#550]
Class expansion does not work as expected in Sublime Text 3

With the following line:
`p.class1.class2.class3` 

Expected:
`<p class="class1 class2 class3"></p>`

Actual:
`p.class1.<class2 class="class3"></class2>`

- Sublime Text 3 Version  _3.1.1, Build 3176_
- OS Version: Windows 10

**Comment by sergeche** [comment]
Make sure you’re actually installed and use Emmet, it seems like a default snippet expansion in Sublime Text
