### ISSUE TITLE
Current project status

### ISSUE THREAD

**Issue by DanielRuf** [emmetio/emmet#551]
Hi, what is the current status of this project? Is it still actively maintained or are you looking for maintainers?

**Comment by sergeche** [comment]
What do you mean by ”looking for maintainers”? Project is open source, anyone can contribute

**Comment by DanielRuf** [comment]
Sure but the last commit was over a year ago and it is currently just you and there are open PRs and issues which are a blocker for new projects.

https://github.com/emmetio/emmet/graphs/contributors
https://github.com/orgs/emmetio/people

Is it just you who has push rights?

**Comment by sergeche** [comment]
Project is currently developed in v2 branch: https://github.com/emmetio/emmet/tree/v2
Will eventually replace `master` branch.
All other repos are considered deprecated
