### ISSUE TITLE
LineBreakOnlyAction is css and XML syntax unique

### ISSUE THREAD

**Issue by hanspistorstetson** [emmetio/emmet#553]
The line break only action will automatically return false if the syntax of the document is not .html, .xml, .xhtml or .css. This causes problem when working with HTML in javascript. 

What is the reason for the check and can it be removed?

**Comment by hanspistorstetson** [comment]
The code in question is at lib/action/lineBreaks.js line 82

**Comment by sergeche** [comment]
You shouldn’t you this repo anymore, there’s newer, modular version: https://github.com/emmetio/expand-abbreviation

Such actions should be implemented for each editor exclusively, if required

**Comment by hanspistorstetson** [comment]
This is the emmet package that atom-emmet uses. Do you know if their are plans to update the package?

**Comment by sergeche** [comment]
https://github.com/emmetio/atom-plugin

**Comment by hanspistorstetson** [comment]
Thank you! I'll be sure to keep an eye on it!
