### ISSUE TITLE
Feature request: Change tag

### ISSUE THREAD

**Issue by robertjk** [emmetio/emmet#564]
A feature I find missing in Emmet is changing tag type.

Let's say I have a `<div>`:

```html
<div class="header>
  ...
</div>
```

At some point I decide to change `<div>` to `<head>`:

```html
<head class="header">
  ...
</head>
```

I do this operations a lot whenever I'm writing HTML. So far I don't know of any quick way to do it other than editing both closing and opening tags separately and that can get quite hard, when the opening and closing tag are far away. Would be great if Emmet supported this.

**Comment by sergeche** [comment]
In some editors, such action is already available as Rename Tag. In next release, I’ll try to make it more user-friendly

**Comment by robertjk** [comment]
Likely it is available in some editors. I use Vim and Vim doesn't a native functionality like this.

I don't know about your attitude towards functionality of Emmet, but it seems to me for a tool like this it's better to not make assumptions about what's in editors or not, but instead trying to offer a complete set of functionality a person editing HTML/XML needs. Then the user of editor A can omit functionality X from Emmet if it's available in his editor, but user of editor B will use X from Emmet as his editor doesn't support it. For example Vim does natively support merging lines and going to a matching tag, but I guess some editors don't and that's why Emmet offers this functionality.

But that's just my take on it.

**Comment by sergeche** [comment]
Everything depends on available editor API, it’s not possible to implement every feature in every editor.

BTW, Vim plugin is implemented by third-party developer so it depends how close plugin developer follows official implementation: https://github.com/mattn/emmet-vim

**Comment by robertjk** [comment]
Yes, plugin for Vim is third-party. But I assumed it's not wise to request a feature in Vim plugin, if it's not available natively in Emmet, so I made a feature request here. Likely if you implement it in native Emmet, Vim plugin will then port it. Maybe I'd be even able to help.

**Comment by sergeche** [comment]
Basically, Emmet is just an abbreviation expander, every plugin vendor decides what features to implement in editor plugin. This is not something that implemented in core package and used everywhere

**Comment by robertjk** [comment]
I thought Emmet as a tool aimed to help in writing HTML; with abbreviation expansion it's most important but not the only one feature. As changing tag type is a very common operation when writing HTML, I though it'd be good idea to add it to Emmet.

**Comment by sergeche** [comment]
As I mentioned earlier, this feature is already implemented in some editors as a part of Emmet plugin

**Comment by robertjk** [comment]
I was just thinking it might be a good idea to add it as a core feature. If you don't think that, no problem and simply close this issue.

**Comment by sergeche** [comment]
New Emmet is just an abbreviation expander + some tools to build various editor actions. I agree tag rename feature is very useful and it will be definitely re-implemented in future versions.

But for now you should create and issue in Vim plugin repo to support it

**Comment by robertjk** [comment]
Fair enough. Thanks for all the explanations. I'm closing this issue.
