### ISSUE TITLE
Change output of shortcut

### ISSUE THREAD

**Issue by arturocuya** [emmetio/emmet#565]
Hello. This is a question not a bug report. I use vim in my workflow and I'd like to change the output of the shortcuts to add a custom indicator. I have vim configured to jump to the next `<++>` whenever i press `,,` in insert mode. I'd like to change the output of,for example:
`a -> <a href="<Cursor>"></a>`
to:
`a -> <a href="<Cursor>"><++></a>`
So that i can jump to the interior of the tag after filling its properties. How could I do that?

**Comment by sergeche** [comment]
You should address this issue to emmet-vim author: https://github.com/mattn/emmet-vim/
