### ISSUE TITLE
Bug: Abbreviations with unbalanced brackets inside text node don't get extracted

### ISSUE THREAD

**Issue by devanshj** [emmetio/emmet#570]
```
import extract from "src/extract-abbreviation";

console.log(extract('foo div{[}+a{}'));
// actual: { abbreviation: "}+a{}", ... }
// expected: { abbreviation: "div{[}+a{}", ... }
```

**Comment by devanshj** [comment]
Also @sergeche, [`src/extract-abbreviation`](https://github.com/emmetio/emmet/tree/master/src/extract-abbreviation) [isn't getting exported in the bundle](https://unpkg.com/browse/emmet@2.0.0-rc.2/dist/emmet.cjs.js#L4723). So are you going to publish it as `@emmetio/extract-abbreviation`? Otherwise people (eg [vscode](https://github.com/microsoft/vscode-emmet-helper/blob/e609f67744a2d428965f84bd928d412a06f6f3be/src/emmetHelper.ts#L9)) still using `@emmetio/extract-abbreviation` would be unable to use the newer version.

**Comment by sergeche** [comment]
Hmm, it does exports: https://github.com/emmetio/emmet/blob/master/src/index.ts#L40

**Comment by devanshj** [comment]
Ah yes my bad was using the 1.x version. Can confirm on [this StackBlitz](https://stackblitz.com/edit/js-hdxbfj).
