### ISSUE TITLE
Emmet length limitation?

### ISSUE THREAD

**Issue by pratham2003** [emmetio/emmet#577]
Hi,

For some reason the following emmet does not work.

```
table>(tr.prefix-intro>td*1)+(tr.prefix-pro-con>th*1+td*3)+(tr.prefix-key-specs>th[colspan=2]*1+td[colspan=2]*3)+(tr.prefix-key-find-online>th[colspan=2]*1+td*2)
```

Following sub-parts of above expression work.
```
table>(tr.prefix-intro>td*1)+(tr.prefix-pro-con>th*1+td*3)+(tr.prefix-key-specs>th[colspan=2]*1+td[colspan=2]*3)
```

The last part works on its own.
```
tr.prefix-key-find-online>th[colspan=2]*1+td*2
```

Is there a length limitation in emmet preventing the above from working together?

Also is there an emmet validator available?

**Comment by sergeche** [comment]
No, there’s no limitation in abbreviation, it looks like there’s an error in abbreviation extraction.
And no, there’s no separate validator for abbreviation, but new Emmet 2 provides error popups if you entered abbreviation which became invalid: https://github.com/emmetio/sublime-text-plugin
