### ISSUE TITLE
Sublime set Pug abbreviations for Pug(Puthon) source.pypug

### ISSUE THREAD

**Issue by brightwiths** [emmetio/emmet#578]
Hello I read many manual and now can write what I need.
I am using Pug(Python) syntax highlighting in Sublime. By clicking ctrl+alt+shift+P it show that scop:
`source.pypug tag.pug complete_tag.pug entity.name.tag.pug`
Its work ok with Pug syntax highlighting and that scope: 
`text.pug meta.tag.other entity.name.tag.pug`
By this manual https://packagecontrol.io/packages/Emmet I set tab for my scope in sublime-keymap User, by this:
` "context": [
    {
      "operand": "source.pypug", 
      "operator": "equal", 
      "match_all": true, 
      "key": "selector"
    }, `
Now I have that situation: by clicking tab its work partition. !+tab do right pug syntax, img+tab ok but link+tab not, abbr trasform to:
`<link rel="stylesheet" href="">` and I need to click double tab to get abbr to syntax.

Think that problem is that:
1. Emmet see Pug(Python) source.pypug like HTML it some cases. So I want to understand where to set full suppourt of Pug abbr, for Pug(Python) like it works with text.pug.
2. I need double click tab in some situations. Maybe some conflict in config is.

Please write me how to fix it, how to set full Pug abbr for source.pypug.
![Untitled](https://user-images.githubusercontent.com/54640696/71779873-d327c480-2fe0-11ea-83b7-d5d5e837d976.png)

**Comment by brightwiths** [comment]
And sometimes I got HTML abbr transform, sometime PUG, its not stable. For example I tested it on that:
`#page>div.logo+ul#navigation>li*5>a{Item $}` One time HTML transform, another time got PUG transform on tab click.

**Comment by sergeche** [comment]
Try new Emmet 2 plugin (still in beta): https://github.com/emmetio/sublime-text-plugin

**Comment by brightwiths** [comment]
> Try new Emmet 2 plugin (still in beta): https://github.com/emmetio/sublime-text-plugin

Thx you! Its works with Pug(Python) good, its progress) May be you know how to fix in new version / and space after end of string?
![Untitled](https://user-images.githubusercontent.com/54640696/71783849-adb3ae80-3012-11ea-835e-edd236cdd3ca.png)
