### ISSUE TITLE
Add support for CSS class with parenthesis

### ISSUE THREAD

**Issue by welcoMattic** [emmetio/emmet#581]
Is it possible to add support for this syntax : `div.u-bgc(gray-200)`?

Today it produces:
```
<div class="u-bgc">
     <gray-200></gray-200>
</div>
```

However, it should produces:

```
<div class="u-bgc(gray-200)"></div>
```

**Comment by sergeche** [comment]
In Emmet 2, you can escape special characters with `\` anywhere in abbreviation. In your example, the abbreviation is:

```
div.u-bgc.\(gray-200\)
```
