### ISSUE TITLE
Is there a way to get rid of predefined HTML attributes?

### ISSUE THREAD

**Issue by LeaVerou** [emmetio/emmet#582]
Hi all, thank you for creating and maintaining this wonderful project!

Is there a way to avoid the predefined attributes in `<textarea>`? Currently expanding `textarea` produces `<textarea name="" id="" cols="30" rows="10"></textarea>`, however `cols` and `rows`, while not yet deprecated, are discouraged, as they are presentational attributes and the dimensions of the element are typically controlled with CSS. Furthermore, `name` and `id` are often not needed either. As it currently stands, I have resolved to typing `textareaa`, then deleting the extra `a`, because it's quicker than deleting all the extra attributes.
Is there a setting somewhere, or perhaps a customizable list of abbreviations? Or would the best way be to send a PR to fix this one?

Thanks!

**Comment by Kravimir** [comment]
Yes, Emmet is customizable in that way. HTML abbreviations are set in "[snippets/html.json](https://github.com/emmetio/emmet/blob/master/snippets/html.json)" and CSS abbreviations are set in "[snippets/css.json](https://github.com/emmetio/emmet/blob/master/snippets/css.json)".

Do you know of an authoritative source that discourages the use of the `cols` and `rows` attributes?

Out of curiosity, which text editor do you use Emmet in?

**Comment by LeaVerou** [comment]
Thank you, this is great!

> Out of curiosity, which text editor do you use Emmet in?

I use Atom.

> Do you know of an authoritative source that discourages the use of the cols and rows attributes?

I just checked and I can't find one, which is surprising. Regardless, even if not explicitly discouraged, developers rarely use them these days, since their primary use case in the past was to control visual width and height.
In any case, I'm not trying to convince anyone to change Emmett! If it's customizable, that's good enough for me :) I'm gonna go ahead and close this now. :)
