### ISSUE TITLE
Self closing of tag

### ISSUE THREAD

**Issue by kunalkendrekar115** [emmetio/emmet#585]
How can we do self closing of empty html tags

**Comment by sergeche** [comment]
Add slash at the end of tag: `foo>bar/`

**Comment by kunalkendrekar115** [comment]
I tried with this but now closing slash is not getting added to tag: <bar>

**Comment by sergeche** [comment]
Do you use this lib directly or use Emmet as editor plugin?

**Comment by kunalkendrekar115** [comment]
I use this library directly ....

**Comment by sergeche** [comment]
The please provide full usage example
