### ISSUE TITLE
Better validation for abbreviation

### ISSUE THREAD

**Issue by sergeche** [emmetio/emmet#586]
Seems like some invalid characters like `?` are considered valid by Emmet, should check it out

**Comment by sergeche** [comment]
Fixed

**Comment by UziTech** [comment]
Why was this a problem?

**Comment by sergeche** [comment]
Since Emmet is used to expand word-like expressions in text, words like `why?` where mistakenly handled as abbreviations. The `?` character was never allowed in element/snippet name.

However, you can preprocess abbreviation before passing it to Emmet: add `\` character before `?` to escape it or use `$variable` instead of `?`

**Comment by UziTech** [comment]
What do you mean by use `$variable`? That seems to turn into `1variable`.

**Comment by sergeche** [comment]
Try `${variable}`

Отправлено с iPhone

**Comment by UziTech** [comment]
That just throws the error: `InvalidCharacterError: "1" did not match the Name production: Unexpected syntax in top`. Also `{}` is the syntax for expanding to [text](https://docs.emmet.io/abbreviations/syntax/#text).

I'm wondering why emmet shouldn't expand `why?` to `<why?></why?>`? If that is what the user chooses to expand what is the problem with expanding it?

**Comment by sergeche** [comment]
> That just throws the error: InvalidCharacterError: "1" did not match the Name production: Unexpected syntax in top. Also {} is the syntax for expanding to text.

Here’s an example of variable usage: https://github.com/emmetio/emmet/blob/master/snippets/html.json#L147

> I'm wondering why emmet shouldn't expand why? to <why?></why?>? If that is what the user chooses to expand what is the problem with expanding it?

Check out how new Emmet works: https://github.com/emmetio/codemirror-plugin#expanding-abbreviations
When user types text it tries to detect if entered text is an abbreviation or not. With this approach, it’s important to reduce false matches to not annoy users. `why?` is an example of such false match.

**Comment by UziTech** [comment]
Oh you meant to replace `${variable}` in the string before sending the string to emmet? That would require escaping the input so it doesn't get confused as part of the abbreviation. Is there an easy way escape a string so it doesn't get confused as emmet syntax?

**Comment by sergeche** [comment]
No, Emmet natively supports variables and replaces them on expand. Although they are not allowed everywhere, only in text and attribute values.

Also, you can escape `?` character before passing it to Emmet to keep your current syntax in emel. Emmet should consume any escaped character no matter of context

**Comment by UziTech** [comment]
> Emmet natively supports variables and replaces them on expand.

Where is this documented?

> Also, you can escape ? character before passing it to Emmet

That is the only way I could think to fix it.

**Comment by sergeche** [comment]
https://docs.emmet.io/customization/snippets/#variables

**Comment by UziTech** [comment]
This fix seems like it should be something that is checked on the format side instead of when creating abbreviations. Since emmet can output html, haml, slim, pug, and maybe other syntaxes in the future, I don't see why `why?` couldn't be a valid tag name for a future syntax.

**Comment by sergeche** [comment]
`why?` in input for Emmet, output can be anything. The goal is to keep same input for different outputs

**Comment by UziTech** [comment]
Thanks for your help. And the very useful library.
