### ISSUE TITLE
Check `lstn` abbreviation in stylesheet 

### ISSUE THREAD

**Issue by sergeche** [emmetio/emmet#591]
Expected result of `lstn` is `list-style-type: none`, but got `list-style-type: n;` instead

**Comment by theperfectpunk** [comment]
@sergeche we can close this as this is already fixed by [5f8782b](https://github.com/emmetio/emmet/commit/5f8782bc84cd28169b11eb05ea05291d735d8ae9)

**Comment by sergeche** [comment]
Thanks!
