### ISSUE TITLE
Typing `posa` (or similar) in stylesheet no longer works

### ISSUE THREAD

**Issue by Edeltraudt** [emmetio/emmet#594]
Need to type pos [tab] a [tab] right now, though e.g. `db` for `display: block` works.

Similar issues for:
* other `position` shortcuts, i.e. `posr`, `poss`
* `aic` for `align-items: center`

Bug appears in most recent emmet version in Sublime Text 3 (v2.1.2)

**Comment by sergeche** [comment]
It appears that you use SCSS syntax, there’s an issue: https://github.com/emmetio/sublime-text-plugin/issues/45#issuecomment-678801693
