### ISSUE TITLE
after latest update Emmet doesn't work at all

### ISSUE THREAD

**Issue by Max-Enrik** [emmetio/emmet#596]
What am I have to do to fix this issue?
I don't have any clue to check something to fix it by myself.

_(Windows x64 ST3 3.2.2)_

**Comment by sergeche** [comment]
Try to restart ST, then open ST console and send me its contents

**Comment by Max-Enrik** [comment]
I use Emmet for many years but first time emmet hotkeys cleaned after update. Now I added again it works fine.
I'll ask when this happen again.

Thank you so much.
_(sorry for delay)_

**Comment by sergeche** [comment]
It shouldn't happen anymore. Previously, Emmet had too many shortcuts which override default actions or actions from other packages. ST itself doesn't provide any means to unbind actions in package and many users complained about it

**Comment by Max-Enrik** [comment]
Oh! I didn't aware of it that override default actions. I am so glad to that it shouldn't happen again. Thank you so much more for your time. Really highly appreciate that.
