### ISSUE TITLE
wrap code html dosnt work anymore  (ctrl+alt+enter)

### ISSUE THREAD

**Issue by zdimaz** [emmetio/emmet#600]
wrap html dosnt work anymore  (ctrl+alt+enter)

**Comment by sergeche** [comment]
https://github.com/emmetio/sublime-text-plugin#more-actions

**Comment by kmgdevelopment** [comment]
Maybe I'm missing something here but I opened _Preferences > Package Settings > Emmet > Key Bindings_ and added the following to the user file (I'm on a Mac):

```
{
  "keys": ["ctrl+w"],
  "command": "emmet_wrap_with_abbreviation",
  "context": [{"key": "setting.is_widget",  "operand": false }]
}
```

But when I hit CTRL+W nothing happens.

**Comment by sergeche** [comment]
@kmgdevelopment make sure your keybindings file is valid. The full file content should look like this:

```json
[{
  "keys": ["ctrl+w"],
  "command": "emmet_wrap_with_abbreviation",
  "context": [{"key": "setting.is_widget",  "operand": false }]
}]
```
