### ISSUE TITLE
Green Auto Suggestion (I don't know what this is called)

### ISSUE THREAD

**Issue by llahnoraa** [emmetio/emmet#603]
With new Emmet update, I kept getting weird green auto suggestion. See screenshot attach. How do I get rid of this? 
<img width="355" alt="green" src="https://user-images.githubusercontent.com/732060/94149954-8c1b8100-fe46-11ea-87f0-27c3a717d3b8.png">

I uninstalled and re-installed and it's still there. If I removed emmet, it doesn't show green thing anymore.

I'm on latest sublime v3.2.2 and latest Emmet v2.1.20

**Comment by sergeche** [comment]
https://github.com/emmetio/sublime-text-plugin#readme

**Comment by llahnoraa** [comment]
Thank you! I had no idea it's called `auto_mark` so I disabled it. Keep up the great work!

**Comment by sergeche** [comment]
Actually, `auto_mark` used to capture abbreviations as you type so you can expand it with Tab key. You need `abbreviation_preview` option which is used to display preview (if you want to keep Tab expander, of course).

**Comment by llahnoraa** [comment]
@sergeche **thank you again!** I just re-enabled `auto_mark` but disabled `abbreviation_preview` and is working as expected.
