### ISSUE TITLE
How to create color with abbreviation ?

### ISSUE THREAD

**Issue by yufeiluo** [emmetio/emmet#604]
The expression:

    `bd1 s `

will expanded as 

    `border: 1px solid #000;`

How to write the abbreviation for  

    `border: 1px solid #dcd2ba;`

**Comment by sergeche** [comment]
bd1-s#dcd2ba

**Comment by yufeiluo** [comment]
Can't work in my vim+emmet.

**Comment by sergeche** [comment]
You should report it to Vim plugin developer
