### ISSUE TITLE
cr and cra not mapping to color

### ISSUE THREAD

**Issue by rzhao271** [emmetio/emmet#610]
c:r and c:ra used to map to color: https://docs.emmet.io/cheat-sheet/
I know that the colon got removed, so now it should be cr and cra that map to color. 

However, those snippets are not in the current CSS snippets file.

**Comment by sergeche** [comment]
Thanks, looks like I missed it somehow, will add them

**Comment by rzhao271** [comment]
Fixed in ebcf1e6!
