### ISSUE TITLE
HTML Wrapping with nodes within text results in improper formatting

### ISSUE THREAD

**Issue by rzhao271** [emmetio/emmet#611]
As an example, I have the current UserConfig:

```js
const config: UserConfig = {
    type: 'markup',
    syntax: 'html',
    text: '<li>test</li>',
    options: {
        'inlineElements': [],
        'output.format': true,
        'output.formatLeafNode': true,
        'output.inlineBreak': 1
    }
};
```

Then, `expand('ul', config)` results in `<ul><li>test</li></ul>` rather than `<ul>\n\t<li>test</li>\n</ul>`.

Another example: wrapping the text `<p><span>test</span></p>` with `ul>li>div` results in `<ul>\n\t<li>\n\t\t<div><p><span>test</span></p></div>\n\t</li>\n</ul>`. Notice there's no newline between the `div` and the `p`.
What's happening is the text is treated as a single value, and since there's no newline within the text (https://github.com/emmetio/emmet/commit/5524ee127f2feec15fbfd39a720f002da90cb6e6), the text isn't indented on its own line.

My main question is whether these outputs are intended behaviour? 
My expectation (which I see Sublime following) was that if the text starts _and_ ends with a node, then it should be on its own line. For example, if the text is `<span>test</span><b>test</b>`, then it should go onto its own line when wrapped.

**Comment by sergeche** [comment]
A JS version is a bit out of sync with Python version. Yes, if text starts with HTML tag it’s assumed that we’re wrapping HTML fragment and output should have newlines. Here’s related commit in Python implementation: https://github.com/emmetio/py-emmet/commit/3f82659c106db3abaf923cb87610490b21e5d0bb
