### ISSUE TITLE
URL not inserted into href for links

### ISSUE THREAD

**Issue by rzhao271** [emmetio/emmet#614]
It seems https://github.com/microsoft/vscode/issues/54711 is still an issue on the latest Emmet.
Wrapping `www.google.it` with `a` should result in `<a href="www.google.it">www.google.it</a>`.

I'm guessing https://github.com/emmetio/py-emmet/commit/98fd8acb024bd8a9af23640989fa5776155f5f88 needs to be implemented on this repository?

**Comment by sergeche** [comment]
Yes, this commit should be implemented in JS version
