### ISSUE TITLE
Inline wrapping sometimes results in hanging indents

### ISSUE THREAD

**Issue by rzhao271** [emmetio/emmet#616]
I tried wrapping `text = ['<li>test1</li>', '<li>test2</li>']` with `div>span*` to obtain

```html
<div>
        <span>
                <li>test1</li>
        </span>
        <span>
                <li>test2</li>
        </span>
</div>
```

but instead I get

```html
<div><span>
        <li>test1</li>
    </span></span>
        <li>test2</li>
    </span></div>
```

A more extreme version of the indent not returning to the starting position occurs when attempting to wrap that same `text` with `span>span>span`.

**Comment by sergeche** [comment]
Technically, it’s not valid use case: wrapping block elements with text elements. I guess I’ll keep it as-is and fix if users would complain
