### ISSUE TITLE
Question about trimming lines before passing to wrap

### ISSUE THREAD

**Issue by rzhao271** [emmetio/emmet#617]
If I wrap `['<div>', '\t<p>test2</p>', '</div>']` with `div` I get the expected indentation. However, if I leave off the tab, the indentation fails and the `<p>test2</p>` line is at the same indent level as the inner `<div>` block.

I'm guessing this means the lines should be trimmed, but that indentation must be preserved before passing it on to Emmet?

**Comment by sergeche** [comment]
Yes, editor should trim contents first before passing it to Emmet

**Comment by sergeche** [comment]
Also note that if user didn’t select anything, editor should match tag and either pass it or its contents, depending on caret position

**Comment by rzhao271** [comment]
Yep, those two parts I understand.
The part I'm not sure about is whether I'm supposed to preserve the tabs at the beginning, or whether I trim them too, before passing them to Emmet?

**Comment by sergeche** [comment]
Yes, it’s up to editor plugin to decide which text lines should be wrapped. ST plugin trims whitespace and list markers from incoming text
