### ISSUE TITLE
CSS abbreviations with ":n" value should expand to "none"

### ISSUE THREAD

**Issue by rzhao271** [emmetio/emmet#628]
From https://github.com/microsoft/vscode/issues/84608.
Should be fixable by skimming through the css snippets file, will take a look shortly.

Edit: Not all abbreviations actually take none. I can write a scraper for https://developer.mozilla.org/en-US/docs/Web/CSS/Reference#Index and see which ones take "none" if that helps.

**Comment by rzhao271** [comment]
Closing since I noticed you already added a fix at https://github.com/emmetio/emmet/commit/5f8782bc84cd28169b11eb05ea05291d735d8ae9.

**Comment by theperfectpunk** [comment]
> Reopening: `bg:n` still expands to `background: no-clip;` rather than `background: none`.

@rzhao271 #696 fixes it, we can close the issue If there are no other observations.
