### ISSUE TITLE
Wrapping text to new lines when clicking on TAB

### ISSUE THREAD

**Issue by rah-emil** [emmetio/emmet#633]
My custom settings:
`{
	"comment": true,
	"telemetry": false,
	"uid": "xxxxxxxx" // I hide
}`

![ScreenRecorderProject1-min](https://user-images.githubusercontent.com/40515235/100125906-60d90080-2e8e-11eb-9fee-468ffbbf4ef5.gif)

**Comment by rah-emil** [comment]
CSS & SASS has a similar problem

**Comment by sergeche** [comment]
Looks like you’re in tabstop mode, hit Esc to exit

**Comment by rah-emil** [comment]
This is not the problem. Escape doesn't help. This has been happening almost constantly since the release of a new version. At first it was all the same, but then it got tired.

**Comment by sergeche** [comment]
You can run `sublime.log_commands(True)` in ST console and check which commands run wget you hit Tab

**Comment by rah-emil** [comment]
> You can run `sublime.log_commands(True)` in ST console and check which commands run wget you hit Tab

I'll check later ;)

**Comment by rah-emil** [comment]
> You can run `sublime.log_commands(True)` in ST console and check which commands run wget you hit Tab
When I create new blocks with Emmet, the command is called `command: next_field` until the commented block ends.
And then it returns to normal, and the command is called `command: reindent`

**Comment by sergeche** [comment]
`command: next_field` means you’re traversing between tabstops, generated by Emmet. You should hit `Esc` key to exit it, same as with regular ST snippets

**Comment by rah-emil** [comment]
Can I turn it off?

**Comment by sergeche** [comment]
No, there’s no such option
