### ISSUE TITLE
Preference "css.valueSeparator" not working

### ISSUE THREAD

**Issue by tobipch** [emmetio/emmet#635]
I have the following VSCode User Preferences (settings.json).

`{
    "emmet.preferences": {
        "css.valueSeparator": ":"
    }
}`

But even after a restart of VSCode, emmet abbrevations get expanded with a space after a colon:
**tac -> text-align: center;**

But with the setting above it should be:
**tac -> text-align:center;**

**Comment by sergeche** [comment]
You should address this issue to VSCode devs, they have their own implementation
