### ISSUE TITLE
Is there any hidden restrictions in the multiplication syntax?

### ISSUE THREAD

**Issue by ferrinweb** [emmetio/emmet#636]
There is such a situation:

```html
<!-- When I press Tab key, this statement can generate fragments normally: -->
li[style='--line-index:$']*36

<!-- When I press Tab key, nothing happens to this statement: -->
li[style='--line-index:$']*360
```
so, i want to know if there is any hidden restrictions in the multiplication syntax?

**Comment by rzhao271** [comment]
Check out the `maxRepeat` field here https://github.com/emmetio/emmet/blob/master/src/config.ts#L59.

If you're using VS Code, the `maxRepeat` field recently got increased, so you should be able to expand that abbreviation now.
