### ISSUE TITLE
No need to replace 'class' attributes with 'className' in vue jsx/tsx.

### ISSUE THREAD

**Issue by weineel** [emmetio/emmet#639]
### Current implementation.

[addon/jsx/rename](https://github.com/emmetio/emmet/blob/51757fc77ee2477c2e2cc6abeff44e64c8a85eec/src/markup/addon/jsx.ts#L14)

### Suggestion

Provide a preference definition attribute rename.

Such as:

1. Default

```
{
	"attribute.rename": {
		"class": "className",
		"for": "htmlFor"
	}	
}
```

2. Customize in vue jsx

```
{
	"attribute.rename": {
		"class": "class",
		"for": "for"
	}	
}
```

**Comment by sergeche** [comment]
JSX transform should be applied in JSX-syntaxes only. No need to apply it in Vue

**Comment by weineel** [comment]
I see. My IDE is vscode, it does not allow to override the `jsx.enabled` option. 

https://github.com/microsoft/vscode-emmet-helper/blob/ee3480d188fc622a187a70c04629e9a74ca262f6/src/emmetHelper.ts#L649

**Comment by weineel** [comment]
I fixed this in vscode settings.

https://github.com/microsoft/vscode-emmet-helper/issues/48

**Comment by wenfangdu** [comment]
@weineel With your fix, expanding `<img>` would produce `<img src="" alt="">` not `<img src="" alt="" />` (notice `/` at the end). So it's not a complete solution. 

@sergeche Could you please consider adding a special case for this? i.e. produce `class` and `for` as they are while preserving the self-closing behavior for JSX.

**Comment by sergeche** [comment]
Element self-closing is controlled via output profile settings

**Comment by wenfangdu** [comment]
@sergeche Thanks, I've figured it out:

```json
{
  "emmet.includeLanguages": {
    "javascriptreact": "html",
    "typescriptreact": "html"
  },
  "emmet.syntaxProfiles": {
    "html": {
      "self_closing_tag": true
    }
  }
}
```

**Comment by wenfangdu** [comment]
I've answered this [here](https://stackoverflow.com/a/68696877/7881859).

**Comment by Ciantic** [comment]
There is no fix here. This should be reopened. Vue is not only JSX library using `class` instead of `className`, e.g. solidjs uses `class` too. It should be configurable.

Using `"typescriptreact": "html",` will break so many other things with JSX.
