### ISSUE TITLE
CSS @f expansion results in multiple cursors

### ISSUE THREAD

**Issue by rzhao271** [emmetio/emmet#640]
Currently, for CSS, `@f` expands to 
`@font-face {\n\tfont-family: ${1};\n\tsrc: url(${1});\n}` (https://github.com/emmetio/emmet/blob/master/snippets/css.json#L2).

I am wondering whether both of them should really be `${1}`? I don't write much CSS, but I feel that a user would typically write in different values for those two fields.

**Comment by sergeche** [comment]
Indeed, should be `${2}` in second case, fixed in v2.3.2
