### ISSUE TITLE
Emmet problem

### ISSUE THREAD

**Issue by kobnuhok** [emmetio/emmet#659]
Проблема с Emmet в sublime text 3
Как в Emmet редактировать сниппет?
У меня получилось сделать чтобы работал при нажатии tab как свойство,а просто как тег не создаётся

**Comment by kobnuhok** [comment]
😥

**Comment by sergeche** [comment]
https://github.com/emmetio/sublime-text-plugin#adding-custom-emmet-snippets
В целом неплохо бы более подробно описывать, что делаете, что ожидаете получить и что не так

**Comment by kobnuhok** [comment]
![IMG20210701145837](https://user-images.githubusercontent.com/77298941/124287757-11139380-db59-11eb-882e-76b75ee7ce41.jpg)
Вот так не работает сниппет 

![IMG20210701145857](https://user-images.githubusercontent.com/77298941/124287859-2f798f00-db59-11eb-8ed3-261180c9808c.jpg)
![IMG20210701145902](https://user-images.githubusercontent.com/77298941/124287869-31435280-db59-11eb-997e-bb637474196a.jpg)
 Вот так работает при подстановке в Emmet  кода. 
Без Emmet ,когда настраиваю сниппет только в sublime, всё работает.
Как сделать чтобы работало не как свойство, а как нормальный сниппет(как тег)

**Comment by sergeche** [comment]
В данном случае лучше использовать нативный ST сниппет, в Emmet нет необходимости для такого контекста. Новая версия специально оптимизирована, чтобы лучше работать с нативными сниппетами

**Comment by kobnuhok** [comment]
Можно подробнее что за ST сниппет или где посмотреть информацию?

**Comment by sergeche** [comment]
https://sublime-text-unofficial-documentation.readthedocs.io/en/stable/extensibility/snippets.html

**Comment by kobnuhok** [comment]
Ааа
Ну я понял,так делал работает 
Но расширить хотябы частично до emmet
Привык уже к некоторым сокращениям и вообще ускоряет разработку

**Comment by kobnuhok** [comment]
2 форум где не могут помочь.
Беда

**Comment by sergeche** [comment]
В чем проблема использовать нативные сниппеты длп данного случая? Они для этого и создавались

**Comment by kobnuhok** [comment]
Где бы их взять, чтобы самому не писать с нуля?
Или я тупой 😁

**Comment by sergeche** [comment]
Я не понимаю, что вы хотите. В ST есть автокомплит по значениям СSS-свойства, есть возможность создавать свои сниппеты. В чем проблема?

**Comment by kobnuhok** [comment]
Говорю тупой я😂
Нужно чтобы работало нормально
Проблема в том что сейчас голый буду пробовать и там смотреть что нужно будет

**Comment by kobnuhok** [comment]
И проблема в том что лень самому писать эти сниппеты,но придётся

**Comment by kobnuhok** [comment]
Спасибо Сергею, убедил всё сделать самому, без Emmet

**Comment by kobnuhok** [comment]
Решается добавлением сниппета в Emmet.
Образец есть YouTube канал фрилансер по жизни. Видео Sublime text 3 настройка установка плагинов. С 21минуты
