### ISSUE TITLE
Support tailwind css arbitrary values

### ISSUE THREAD

**Issue by mortezasabihi** [emmetio/emmet#674]
It's nice to add tailwindcss arbitrary values support.

Example:
```
.mr-[500px]
```
Translates to:
```
<div class="mr-[500px]"></div>
```

**Comment by morigs** [comment]
Looks like it currently works with escaping

```
div.mr-\\[500\\]
```

**Comment by morigs** [comment]
Btw it looks like Emmet needs a special mode for tailwind classes (without escaping) because they are invalid according to W3C spec:

> In CSS, identifiers (including element names, classes, and IDs in selectors) can contain only the characters [a-z0-9] and ISO 10646 characters U+00A0 and higher, plus the hyphen (-) and the underscore (_); they cannot start with a digit, or a hyphen followed by a digit. Identifiers can also contain escaped characters and any ISO 10646 character as a numeric code (see next item). For instance, the identifier "B&W?" may be written as "B&W?" or "B\26 W\3F".

Tailwind itself uses escaping in the source code for such characters

**Comment by sergeche** [comment]
Thanks to @morigs, users can write complex Tailwind classes without escaping special characters by using a special quoted class syntax:

```
."peer-[:nth-of-type(3)_&]:block"
```

Note that you can combine multiple classes as well:


```
.p-1."mr-[500px]"
```
