### ISSUE TITLE
Can emmet identify vue style code block? Here is a UE problem.

### ISSUE THREAD

**Issue by mollerzhu** [emmetio/emmet#682]
When I input
`.test{}`
in *.vue <style> tag, and press enter, 
the result is :
`<div class='test'></div>`
BUT, I want 
```
.test{
     
}
```
How can i fix it???

**Comment by sergeche** [comment]
Please specify editor you are using

**Comment by mollerzhu** [comment]
> Please specify editor you are using

VSCODE

**Comment by mollerzhu** [comment]
OK，thx
