### ISSUE TITLE
when we use video the controls attribute does not come by itself

### ISSUE THREAD

**Issue by ayushnau** [emmetio/emmet#683]
when we use video the controls attribute does not come by itself though it is common to use controls in it.

**Comment by sergeche** [comment]
Not sure what you mean. What's the issue with video?

**Comment by Ayush2020012016** [comment]
i am talking about video tag  <video src=""></video> comes. instead i thing controls tag should come along with it. like this 
<video control src=""></video> as it is common to use control along with video tag

**Comment by Ayush2020012016** [comment]
> Not sure what you mean. What's the issue with video?

i am talking about video tag comes. instead i thing controls tag should come along with it. like this
as it is common to use control along with video tag

**Comment by sergeche** [comment]
You can modify Emmet abbreviations for yourself or create a new abbreviation with `controls` attribute by default.

In many cases `controls` is not required so I don't see any reason to include it by default
