### ISSUE TITLE
Please! There're any chance to publish releases rather than only tags

### ISSUE THREAD

**Issue by herunlei** [emmetio/emmet#685]
Hi,

Just want to know if there are any plan to publish releases rather then the tags, thanks!

**Comment by sergeche** [comment]
Not sure what you mean by publishing releases

**Comment by herunlei** [comment]
Thanks for replay. I mean github project release, ref to this link https://docs.github.com/en/repositories/releasing-projects-on-github/about-releases

**Comment by sergeche** [comment]
You mean release notes? Or what release do you need, an npm package?

**Comment by herunlei** [comment]
Yes, release with release notes, like you did years before.
![image](https://user-images.githubusercontent.com/15745963/177279467-408776d3-b747-4980-a2a9-743fac3d03e9.png)
