### ISSUE TITLE
Support for SolidJS (JSX)

### ISSUE THREAD

**Issue by laureanray** [emmetio/emmet#687]
Solid uses `class` instead of `className`. I'm curious if there is already a plan for emmet to support this? Maybe a flag or something since both React and Solid use `js`, `ts`, `tsx`

**Comment by manucorporat** [comment]
Qwik and other JSX dont use `className` either. Please a fix, or configuration would be apreaciated

**Comment by sergeche** [comment]
It’s only a config option. The configuration depends on editor you’re using.
There’s a new feature to override attributes in Emmet: https://github.com/emmetio/py-emmet/blob/master/CHANGELOG.md#attributes-override

**Comment by laureanray** [comment]
Thanks @sergeche, closing this issue now.
