### ISSUE TITLE
meta:vp should not disable zoom

### ISSUE THREAD

**Issue by tkrotoff** [emmetio/emmet#688]
`meta:vp` is defined as `<meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0" />` which disables zoom 😱

Should be instead `<meta name="viewport" content="width=device-width">`

https://www.matuzo.at/blog/2022/please-stop-disabling-zoom/

**Comment by querkmachine** [comment]
Unless I'm mistaken, [the definition of `meta:vp` in the snippet code](https://github.com/emmetio/emmet/blob/master/snippets/html.json#L29) doesn't seem to disable user scaling. 

[The cheat sheet](https://docs.emmet.io/cheat-sheet/) is seemingly out of date.

**Comment by elvary** [comment]
https://www.reddit.com/r/webdev/comments/x0hgbv/stop_disabling_zoom_on_your_mobile_sites/
saw a mention to this issue on reddit and im here to give an upvote👍🏻

**Comment by sergeche** [comment]
There’s no disabled zoom in snippets for about 2 years already: https://github.com/emmetio/emmet/blob/master/snippets/html.json#L29
