### ISSUE TITLE
attributeQuotes - option for none or curly brackets

### ISSUE THREAD

**Issue by dericbytes** [emmetio/emmet#700]
In react native you have curly brackets.

Also none would be useful for a personal project.

 'output.attributeQuotes': 'curlyBrackets',

 ```<View style={styles.container} />```

double quotes

 ```<View style={{backgroundColor: 'red', flex: 0.5}} />```

if string or number, wrapping in {} is optional

```<MaterialIcons name={icon} size={24} color="#fff" />```

**Comment by dericbytes** [comment]
Thanks. I am using a different editor and writing a nodejs script. What options do I need to send

```
expand('v[style=foo color=23]>t*3',
		   {
		     syntax: 'my-custom-syntax',
		     type: 'jsx',
		     snippets: parseSnippets(snippets),
		     options: {
		       'stylesheet.between': ': ',
		       'stylesheet.after': ';',
                       'output.field': (index, placeholder) => `\${${index}${placeholder ? ':' + placeholder : ''}}`
		     }
})
```

```
<View style="foo" color="23">
	<Text>${1}</Text>
	<Text>${2}</Text>
	<Text>${3}</Text>
</View>

```

**Comment by sergeche** [comment]
In your case, you can expand it like this: `expand('v[style={{foo}} color={23}]>t*3')`

**Comment by dericbytes** [comment]
I get error - Unexpected "Bracket" token at 14, using your example

```'v[style={{foo}} color={23}]>t*3'```

my snippet

```  "v": "View" ```

this got me one step closer - curly bracket worked

```'v[style={foo} color=23]>t*3'```

```<View style={foo} color={23}>
	<Text>${1}</Text>
	<Text>${2}</Text>
	<Text>${3}</Text>
</View>
```

**Comment by sergeche** [comment]
OK, will check it out soon

**Comment by dericbytes** [comment]
I just noticed my code expanded like yours. I was hoping the the 22 would appear with no quoting. Is there a way to achieve this. 

Thanks for our prompt and useful replies.
