### ISSUE TITLE
Add support for <data> tags

### ISSUE THREAD

**Issue by JayWright31** [emmetio/emmet#705]
I've noticed there's no support for `<data>` tags in Emmet. I'm creating this issue to address it and I can start working on it immediately. Should be able to open a PR soon

**Comment by sergeche** [comment]
Not sure which support is expected? Emmet can expand any word into tag, e.g. just type `data` and expand it

**Comment by JayWright31** [comment]
by default the data tag should include a value I believe. So i've added that to make it a bit easier. but I appreciate what you're saying
