### ISSUE TITLE
Support for other JSX frameworks please

### ISSUE THREAD

**Issue by LazyClicks** [emmetio/emmet#718]
Qwik and Solid don't use className but instead use class for example

**Comment by LazyClicks** [comment]
we just need jsx with class instead of classname 
https://github.com/emmetio/emmet/blob/8d66da8c5b64c5283ed9861b16e429716b115da2/src/config.ts#L390-L402

**Comment by sergeche** [comment]
You can override these options in your editor

**Comment by manucorporat** [comment]
how? personally spent a couple hours trying to figure out how to change the jsx markup.attributes from the vscode config without luck. Not documented anywhere

**Comment by manucorporat** [comment]
Lots of things can be configured, but i dont see this one being one of them

**Comment by sergeche** [comment]
It depends on editor you are using

**Comment by sergeche** [comment]
https://github.com/microsoft/vscode/issues/180689

**Comment by manucorporat** [comment]
oh wow! that explains why it was nothing working on my side! we will wait for vscode release
Thank you!! 

Safe to close imo!
