### ISSUE TITLE
Add abbreviation for slot

### ISSUE THREAD

**Issue by anthonyvdotbe** [emmetio/emmet#729]
[slot](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/slot) should be expanded to `<slot name=""></slot>`, with the caret first inside the name attribute and then inside the element itself.

**Comment by sergeche** [comment]
`slot[name]`.

**Comment by anthonyvdotbe** [comment]
AFAIK a slot without a name doesn't have a use case, so that's why I'd like to have just slot be sufficient, equivalent to how just `a` also adds the `href` attribute and expands to `<a href=""></a>`
